many fixes and changes

diff --git a/src/confighelp/confighelp b/src/confighelp/confighelp
--- a/src/confighelp/confighelp
+++ b/src/confighelp/confighelp
@@ -3,11 +3,31 @@
 # Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
 #
 
-SCRIPT_NAME=`basename $0`
+script_name=`basename $0`
+script_dir=`dirname $0`
+
+################################################################################
+# LOAD CONFIG
+PATH=$FORMAKE:$PATH
+CONFIGHELP=
+if test -f $script_dir/config.rc; then
+  . $script_dir/config.rc
+fi
+test -n "$FORMAKE_CONFIGHELP" && CONFIGHELP=$FORMAKE_CONFIGHELP
+if test -n "$CONFIGHELP" && test -z "$CONFIGHELP_REDIRECT"; then
+  export CONFIGHELP_REDIRECT=1
+  $CONFIGHELP "$@"
+  ret=$?
+  if test $ret -ne 64; then
+    exit $ret
+  fi
+fi
+################################################################################
+
 
 print_help() {
   cat <<EOF
-Usage: $SCRIPT_NAME [-install] [-cc] [-cxx]
+Usage: $script_name [-install] [-cc] [-cxx]
   -install   print installation related options
   -cc        print C compilation options
   -cxx       print C++ compilation options
@@ -33,7 +53,7 @@ for param in "$@"; do
       op_install=1
       ;;
     *)
-      echo "$SCRIPT_NAME: error: invalid parameter: $param" >&2
+      echo "$script_name: error: invalid parameter: $param" >&2
       exit 1
       ;;
   esac
diff --git a/src/libro/libro b/src/libro/libro
--- a/src/libro/libro
+++ b/src/libro/libro
@@ -7,6 +7,30 @@ version_string="libro 1.0"
 script_name=`basename $0`
 script_dir=`dirname $0`
 
+################################################################################
+# LOAD CONFIG
+PATH=$FORMAKE:$PATH
+LIBRO=
+AR=
+AR_FLAGS=
+if test -f $script_dir/config.rc; then
+  . $script_dir/config.rc
+fi
+test -n "$FORMAKE_LIBRO" && LIBRO=$FORMAKE_LIBRO
+if test -n "$LIBRO" && test -z "$LIBRO_REDIRECT"; then
+  export LIBRO_REDIRECT=1
+  $LIBRO "$@"
+  ret=$?
+  if test $ret -ne 64; then
+    exit $ret
+  fi
+fi
+test -n "$CONFIG_AR" && AR=$CONFIG_AR
+test -n "$AR" || AR=ar
+test -n "$CONFIG_AR_FLAGS" && AR_FLAGS=$CONFIG_AR_FLAGS
+test -n "$AR_FLAGS" || AR_FLAGS=clq
+################################################################################
+
 print_help() {
   cat <<EOF
 $script_name [static] -name NAME [-ver VERSION] -obj OBJECTS [-o dir] [-p] [-s]
@@ -47,9 +71,9 @@ EOF
 
 mkstatic() {
   if test x$op_print = x; then
-    ar -h >dev/null 2>&1
-    if test $? = 127; then
-      echo "$script_name: ar not found" >&2
+    $AR -h >dev/null 2>&1
+    if test $? -eq 127; then
+      echo "$script_name: $AR not found" >&2
       exit 1
     fi
   fi
@@ -66,7 +90,7 @@ mkstatic() {
   fi
 
   run_command rm -f $lib_static
-  run_command ar clq $lib_static $op_obj
+  run_command $AR $AR_FLAGS $lib_static $op_obj
 }
 
 mkshared() {
@@ -77,11 +101,11 @@ mkshared() {
   fi
   
   $xstem -h >/dev/null 2>&1
-  if test $? -eq 0; then
+  if test $? -ne 127; then
     CSTEM=$xstem
   else
     $script_dir/$xstem -h >/dev/null 2>&1
-    if test $? -eq 0; then
+    if test $? -ne 127; then
       CSTEM=$script_dir/$xstem
     else
       echo "$script_name: error: $xstem not found" >&2
diff --git a/src/mkconfigure/test/formake/optool b/src/mkconfigure/test/formake/optool
--- a/src/mkconfigure/test/formake/optool
+++ b/src/mkconfigure/test/formake/optool
@@ -4,6 +4,25 @@
 #
 
 script_name=`basename $0`
+script_dir=`dirname $0`
+
+################################################################################
+# LOAD CONFIG
+PATH=$FORMAKE:$PATH
+OPTOOL=
+if test -f $script_dir/formake.conf; then
+  . $script_dir/formake.conf
+fi
+test -n "$FORMAKE_OPTOOL" && OPTOOL=$FORMAKE_OPTOOL
+if test -n "$OPTOOL" && test -z "$OPTOOL_REDIRECT"; then
+  export OPTOOL_REDIRECT=1
+  $OPTOOL "$@"
+  ret=$?
+  if test $ret -ne 64; then
+    exit $ret
+  fi
+fi
+################################################################################
 
 sbs_param=
 disable_special=
@@ -13,8 +32,8 @@ no_case_change=
 case x$1 in
   x-h|x-help|x--help)
     cat <<EOF
-Usage: $script_name rc [-p <PREFIX>] [-nc] [-] OPTIONS
-       $script_name def [-p <PREFIX>] [-nc] [-] OPTIONS
+Usage: $script_name dump [-p <PREFIX>] [-nc] [-] OPTIONS
+       $script_name hdump [-p <PREFIX>] [-nc] [-] OPTIONS
        $script_name validate OPTIONS - VALID_OPTIONS
        $script_name if OPTIONS - COND_OPTIONS
        $script_name ifor OPTIONS - COND_OPTIONS
@@ -23,7 +42,7 @@ Usage: $script_name rc [-p <PREFIX>] [-nc] [-] OPTIONS
 EOF
     exit 0
     ;;
-  xrc|xdef)
+  xdump|xhdump)
     mode=$1
     shift
     while test $# -gt 0; do
@@ -31,7 +50,7 @@ EOF
         -*|*=*)
           if test -n "$sbs_param"; then
             test -n "$sbs_param_val$sbs_param_set" || sbs_param_val=1
-            if test $mode = rc; then
+            if test $mode = dump; then
               echo "$sbs_param=\"$sbs_param_val\""
             else
               echo "#define $sbs_param \"$sbs_param_val\""
@@ -48,6 +67,10 @@ EOF
                   exit 1
                 fi
                 op_prefix=`echo -n "$1" | sed 's/[^a-zA-Z0-9_]//g'`
+                if test -z "$op_prefix"; then 
+                  echo "$script_name: error: invalid prefix '$1'" >&2
+                  exit 1
+                fi
                 param_skip=1
                 ;;
               -nc)
@@ -95,7 +118,7 @@ EOF
     done
     if test -n "$sbs_param"; then
       test -n "$sbs_param_val$sbs_param_set" || sbs_param_val=1
-      if test $mode = rc; then
+      if test $mode = dump; then
         echo "$sbs_param=\"$sbs_param_val\""
       else
         echo "#define $sbs_param \"$sbs_param_val\""
@@ -214,7 +237,7 @@ EOF
 #!/bin/sh
 rm -f $tmp_file
 EOF
-    $0 rc "$@" >>$tmp_file
+    $0 dump "$@" >>$tmp_file
     echo -n "$tmp_file"
     ;;
   x)
diff --git a/src/mkdep/mkdep b/src/mkdep/mkdep
--- a/src/mkdep/mkdep
+++ b/src/mkdep/mkdep
@@ -10,6 +10,24 @@ tmp_file=/tmp/dep$$.t
 tmp_file2=/tmp/dep$$.t2
 tmp_file3=/tmp/dep$$.t3
 
+################################################################################
+# LOAD CONFIG
+PATH=$FORMAKE:$PATH
+MKDEP=
+if test -f $script_dir/config.rc; then
+  . $script_dir/config.rc
+fi
+test -n "$FORMAKE_MKDEP" && MKDEP=$FORMAKE_MKDEP
+if test -n "$MKDEP" && test -z "$MKDEP_REDIRECT"; then
+  export MKDEP_REDIRECT=1
+  $MKDEP "$@"
+  ret=$?
+  if test $ret -ne 64; then
+    exit $ret
+  fi
+fi
+################################################################################
+
 print_help() {
 cat <<EOF
 Generate dependencies of C/C++ source files for Makefile
@@ -121,13 +139,14 @@ else
   cstem_cmd="cstem"
 fi
 
-if $cstem_cmd -h >/dev/null 2>&1; then
-  :
-elif $script_dir/$cstem_cmd -h >/dev/null 2>&1; then
-  cstem_cmd=$script_dir/$cstem_cmd
-else
-  echo "$script_name: error. $cstem_cmd not found" >&2
-  exit 1
+$cstem_cmd -h >/dev/null 2>&1
+if test $? -eq 127; then
+  if test -f $script_dir/$cstem_cmd; then
+    cstem_cmd=$script_dir/$cstem_cmd
+  else
+    echo "$script_name: error: $cstem_cmd not found" >&2
+    exit 1
+  fi
 fi
 
 cc_cmd=$op_cc
