big refactoring

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,40 +1,95 @@
 #!/bin/sh
 ################################################################################
-# Generated by Formake mkconfigure
-# Tue Feb 14 23:35:20 EET 2017
+# Generated by mkconfigure
+# Thu Jun  1 20:33:40 EEST 2017
 #
-# mkconfigure -name formake -version 0.9.1
+# mkconfigure -name formake -version 0.9.7 -f
 #
 # Important variables to use:
 #   PACKAGE_NAME     - package (project) name
 #   PACKAGE_VERSION  - package version
 #   CONF             - name of the build config file
-#   CONF_H           - name of the build config header file
 #   SRCROOT          - package source root directory (package top dir)
-#   STD_OPTIONS      - standard configure options
-#   OPTIONS          - custom configure options
-#   VPATH_ON         - set to 1 if configure is run outside of the source root dir
 
 ################################################################################
 # BASE CONFIGURATION
 PACKAGE_NAME="formake"
-PACKAGE_VERSION="0.9.6"
+PACKAGE_VERSION="0.9.7"
 CONF="build.conf"
-CONF_H="build.h"
+MK_CONF="mk.conf"
+DISTCLEAN_FILES="$CONF $MK_CONF configure.log"
 
 ################################################################################
 # PACKAGE PATHES
 SRCROOT=`dirname $0`
-PATH=$FORMAKE:`pwd`/formake:$SRCROOT/formake:$PATH
+PATH=`pwd`/mk:$SRCROOT/mk:$PATH
+
+################################################################################
+# PACKAGE CONSISTENCY
+#
+# Here we check scripts that are used by this script
+excom relpath || exit 1
+
+
+################################################################################
+# IMPORTANT VARIABLES
+#
+SRCROOT=`dirname $0 | xargs relpath ./`
+ABS_SRCROOT=`pwd`/$SRCROOT
 
 ################################################################################
 # OPTIONS
-STD_OPTIONS="-h -help --help -prefix -exec-prefix -bindir -sbindir -libexecdir -libdir -incdir \
-             -etcdir -vardir -sharedir -mandir -docdir"
-OPTIONS=""
+while test $# -gt 0; do
+  param=`echo -n "$1" | sed 's/^--*/-/'`
+  case $param in
+    -h|-help)
+      op_help=1
+      ;;
+    -prefix=*)
+      PREFIX=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -exec-prefix=*)
+      EXEC_PREFIX=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -bindir=*)
+      BINDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -sbindir=*)
+      SBINDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -libexecdir=*)
+      LIBEXECDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -libdir=*)
+      LIBDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -incdir=*)
+      INCDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -etcdir=*)
+      ETCDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -vardir=*)
+      VARDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -sharedir=*)
+      SHAREDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -mandir=*)
+      MANDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    -docdir=*)
+      DOCDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ;;
+    *)
+      echo "$script_name: invalid option: $1"
+      exit 1
+      ;;
+  esac
+  shift
+done
 
-optool validate xh $STD_OPTIONS $OPTIONS - "$@" || exit 1
-if optool test any -h -help --help - "$@"; then
+if test x$op_help = x1; then
   cat <<EOF
 Usage: configure [options]
   --prefix=PREFIX         path to install architecture-independent files [/usr/local]
@@ -52,7 +107,6 @@ Usage: configure [options]
 EOF
   exit 0
 fi
-. `optool source "$@"`
 
 ################################################################################
 # VPATH
@@ -62,20 +116,18 @@ test ! -f `basename $0` && VPATH_ON=1
 ################################################################################
 # INIT BUILD ROOT
 if test x$VPATH_ON = x1; then
-  if test -f $SRCROOT/formake; then
-    rm -Rf formake
-    cp -Rf $SRCROOT/formake ./
-    rm -f formake/*.conf
+  if test -f $SRCROOT/mk; then
+    cp -Rf $SRCROOT/mk ./
+    rm -f mk/*.conf
   fi
 fi
-rm -f configure.log
 
-################################################################################
-# PACKAGE CONSISTENCY
-syscap test relpath mkrule || exit 1
 
 ################################################################################
 # STANDARD DIRECTORIES
+#
+# Set up standard installation directories
+
 test -n "$PREFIX"      || PREFIX=/usr/local
 test -n "$EXEC_PREFIX" || EXEC_PREFIX=$PREFIX
 test -n "$BINDIR"      || BINDIR=$EXEC_PREFIX/bin
@@ -92,32 +144,44 @@ test -n "$DOCDIR"      || DOCDIR=$SHAREDIR/doc
 DOCDIR=$DOCDIR/$PACKAGE_NAME
 DATADIR=$SHAREDIR/$PACKAGE_NAME
 
-################################################################################
-# BUILD CONFIGS
-optool dump "$@" -package-name "$PACKAGE_NAME" -package-version "$PACKAGE_VERSION" \
-            -prefix $PREFIX -exec-prefix $EXEC_PREFIX -bindir $BINDIR -sbindir $SBINDIR \
-            -libexecdir $LIBEXECDIR -libdir $LIBDIR -incdir $INCDIR -etcdir $ETCDIR \
-            -vardir $VARDIR -sharedir $SHAREDIR -mandir $MANDIR -docdir $DOCDIR \
-            -datadir $DATADIR >$CONF
 
 ################################################################################
-# FORMAKE CONFIG
-optool dump -prefix $PREFIX -exec-prefix $EXEC_PREFIX -bindir $BINDIR -sbindir $SBINDIR \
-            -libexecdir $LIBEXECDIR -libdir $LIBDIR -incdir $INCDIR -etcdir $ETCDIR \
-            -vardir $VARDIR -sharedir $SHAREDIR -mandir $MANDIR -docdir $DOCDIR \
-            -datadir $DATADIR \
-            -package-name $PACKAGE_NAME -package-version $PACKAGE_VERSION >formake/formake.conf
+# CREATE BUILD AND MK CONFIG FILES
+cat <<EOF >$CONF
+PACKAGE_NAME="$PACKAGE_NAME"
+PACKAGE_VERSION="$PACKAGE_VERSION"
+PREFIX="$PREFIX"
+EXEC_PREFIX="$EXEC_PREFIX"
+BINDIR="$BINDIR"
+SBINDIR="$SBINDIR"
+LIBEXECDIR="$LIBEXECDIR"
+LIBDIR="$LIBDIR"
+INCDIR="$INCDIR"
+ETCDIR="$ETCDIR"
+VARDIR="$VARDIR"
+SHAREDIR="$SHAREDIR"
+MANDIR="$MANDIR"
+DOCDIR="$DOCDIR"
+DATADIR="$DATADIR"
+SRCROOT="$SRCROOT"
+ABS_SRCROOT="$ABS_SRCROOT"
+EOF
+
+cat $CONF > mk/$MK_CONF
+
 
 ################################################################################
-# SYSTEM DEPENDENCIES
-syscap test install || exit 1
+## CHECK THAT REQUIRED PROGRAMS ARE AVAILABLE
+##
+## Run 'excom -help' to get a full list of options
 
-################################################################################
-# CUSTOM CODE
+## Example. Find programs: ar tar bzip2. Exit if any one not found.
+# excom ar tar bzip2 || exit 1
 
-################################################################################
-# MKMF
-$SRCROOT/mkmf || exit 1
+excom install  || exit 1
+
+
+$SRCROOT/mkmf
 
 ################################################################################
 # FINISH
