initial files for Formake template build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,119 +1,74 @@
 #!/bin/sh
-# JUMP TO MODERN SHELL IF POSSIBLE
-(test_exit_code_127_sdfjsdfksjdhfksjdhf  >/dev/null) 2>/dev/null
-if test $? -ne 127; then
-  if test -z "$FORMAKE_BASH_REDIRECT"; then
-    FORMAKE_BASH_REDIRECTED=1
-    export FORMAKE_BASH_REDIRECTED
-    if test -x /bin/bash; then
-      exec /bin/bash "$0" ${1+"$@"}
-    elif test -x /usr/bin/bash; then
-      exec /usr/bin/bash "$0" ${1+"$@"}
-    elif test -x /usr/local/bin/bash; then
-      exec /usr/local/bin/bash "$0" ${1+"$@"}
-    else
-      (bash -c "pwd" >/dev/null) 2>/dev/null
-      if test $? -eq 0; then
-        exec bash "$0" ${1+"$@"}
-      fi
-    fi
-  fi
-fi
-FORMAKE_BASH_REDIRECTED=
-export FORMAKE_BASH_REDIRECTED
-
 
 ################################################################################
-# Generated by mkconfigure
-# Thu Jun  1 20:33:40 EEST 2017
-#
-# mkconfigure -name formake -version 0.9.7 -f
-#
-# Important variables to use:
-#   PACKAGE_NAME     - package (project) name
-#   PACKAGE_VERSION  - package version
-#   CONF             - name of the build config file
-#   SRCROOT          - package source root directory (package top dir)
-
+# set base project variables
+PACKAGE_NAME="PROJECT_X"
+PACKAGE_VERSION="1.0.0"
+CONFIG_OUT="build.conf"
 
 ################################################################################
-# BASE CONFIGURATION
-PACKAGE_NAME="formake"
-PACKAGE_VERSION="0.14"
-CONF="build.conf"
-MK_CONF="mk.conf"
-DISTCLEAN_FILES="$CONF $MK_CONF configure.log"
-
-################################################################################
-# PACKAGE PATHES
-SRCROOT=`dirname $0`
-PATH=`pwd`/mk:$SRCROOT/mk:$PATH
-
-################################################################################
-# PACKAGE CONSISTENCY
-#
-# Here we check scripts that are used by this script
-excom relpath || exit 1
-
-
-################################################################################
-# IMPORTANT VARIABLES
-#
-SRCROOT=`dirname $0 | xargs relpath ./`
-ABS_SRCROOT=`pwd`/$SRCROOT
-
-################################################################################
-# OPTIONS
+# parse options
 while test $# -gt 0; do
-  param=`echo -n "$1" | sed 's/^--*/-/'`
+  param=`echo "$1" | sed 's/^--/-/'`
   case $param in
     -h|-help)
       op_help=1
       ;;
     -prefix=*)
-      PREFIX=`echo -n "$param" | sed 's/^[^=]*=//'`
+      PREFIX=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -exec-prefix=*)
-      EXEC_PREFIX=`echo -n "$param" | sed 's/^[^=]*=//'`
+      EXEC_PREFIX=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -bindir=*)
-      BINDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      BINDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -sbindir=*)
-      SBINDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      SBINDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -libexecdir=*)
-      LIBEXECDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      LIBEXECDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -libdir=*)
-      LIBDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      LIBDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -incdir=*)
-      INCDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      INCDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -etcdir=*)
-      ETCDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      ETCDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -vardir=*)
-      VARDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      VARDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -sharedir=*)
-      SHAREDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      SHAREDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -mandir=*)
-      MANDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      MANDIR=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     -docdir=*)
-      DOCDIR=`echo -n "$param" | sed 's/^[^=]*=//'`
+      DOCDIR=`echo "$param" | sed 's/^[^=]*=//'`
+      ;;
+    CC=*)
+      CC=`echo "$param" | sed 's/^[^=]*=//'`
+      ;;
+    CFLAGS=*)
+      CFLAGS=`echo "$param" | sed 's/^[^=]*=//'`
+      ;;
+    LDFLAGS=*)
+      LDFLAGS=`echo "$param" | sed 's/^[^=]*=//'`
       ;;
     *)
-      echo "$script_name: invalid option: $1"
+      echo "$0: invalid option: $1"
       exit 1
       ;;
   esac
   shift
 done
 
+################################################################################
+# print help if we received -h or --help parameter
 if test x$op_help = x1; then
   cat <<EOF
 Usage: configure [options]
@@ -129,30 +84,51 @@ Usage: configure [options]
   --sharedir=DIR          share path [PREFIX/share]
   --mandir=DIR            man path [SHAREDIR/man]
   --docdir=DIR            doc path [SHAREDIR/doc]
+  CC=CMD                  C compiler command
+  CFLAGS=FLAGS            C compiler flags
+  LDFLAGS=FLAGS           LD flags
 EOF
   exit 0
 fi
 
 ################################################################################
-# VPATH
-VPATH_ON=
-test ! -f `basename $0` && VPATH_ON=1
+# go to package dir and set up PATH
+cd `dirname "$0"`
+PATH=`pwd`/mk:$PATH
 
 ################################################################################
-# INIT BUILD ROOT
-if test x$VPATH_ON = x1; then
-  if test -f $SRCROOT/mk; then
-    cp -Rf $SRCROOT/mk ./
-    rm -f mk/*.conf
-  fi
+# check that PATH is correct and we have access to the package scripts
+cmdok cltest cppdef cprobe mkdep pofig || exit 1
+
+################################################################################
+# probe build host parameters: OS, OS version, kernel version, distro, distro version, cpu
+# run 'pofig -h' to get help on tool parameters
+HOST_OS=`pofig -o`
+HOST_OS_VERSION=`pofig -s`
+HOST_KERNEL_VERSION=`pofig -k`
+HOST_DISTRO=`pofig -d`
+HOST_DISTRO_VERSION=`pofig -r`
+HOST_ARCH=`pofig -a`
+
+################################################################################
+# check system tools: make install
+cmdok make install || exit 1
+
+################################################################################
+# check if we have valid C compiler and get compiler command
+cprobe $CC >/dev/null || exit 1
+CC=`cprobe $CC -c`
+
+################################################################################
+# check compiler, compiler flags, linker flags
+# run 'cltest -h' to get help on tool parameters
+cltest $CC || exit 1
+if test -n "$CFLAGS$LDFLAGS"; then
+  cltest $CC -cflags="$CFLAGS" -ldflags="$LDFLAGS" || exit 1
 fi
 
-
 ################################################################################
-# STANDARD DIRECTORIES
-#
 # Set up standard installation directories
-
 test -n "$PREFIX"      || PREFIX=/usr/local
 test -n "$EXEC_PREFIX" || EXEC_PREFIX=$PREFIX
 test -n "$BINDIR"      || BINDIR=$EXEC_PREFIX/bin
@@ -169,10 +145,9 @@ test -n "$DOCDIR"      || DOCDIR=$SHAREDIR/doc
 DOCDIR=$DOCDIR/$PACKAGE_NAME
 DATADIR=$SHAREDIR/$PACKAGE_NAME
 
-
 ################################################################################
-# CREATE BUILD AND MK CONFIG FILES
-cat <<EOF >$CONF
+# generate build config file
+cat <<EOF >$CONFIG_OUT
 PACKAGE_NAME="$PACKAGE_NAME"
 PACKAGE_VERSION="$PACKAGE_VERSION"
 PREFIX="$PREFIX"
@@ -188,27 +163,28 @@ SHAREDIR="$SHAREDIR"
 MANDIR="$MANDIR"
 DOCDIR="$DOCDIR"
 DATADIR="$DATADIR"
-SRCROOT="$SRCROOT"
-ABS_SRCROOT="$ABS_SRCROOT"
+
+HOST_OS="$HOST_OS"
+HOST_OS_VERSION="$HOST_OS_VERSION"
+HOST_KERNEL_VERSION="$HOST_KERNEL"
+HOST_DISTRO="$HOST_DISTRO"
+HOST_DISTRO_VERSION="$HOST_DISTRO_VERSION"
+HOST_ARCH="$HOST_ARCH"
+
+CFLAGS="$CFLAGS"
+LDFLAGS="$LDFLAGS"
 EOF
 
-cat $CONF > mk/$MK_CONF
-
+################################################################################
+# probe compiler parameters and save to config file
+# run 'cprobe -h' to get help on tool parameters
+cprobe $CC -1 - $CFLAGS >>$CONFIG_OUT
 
 ################################################################################
-## CHECK THAT REQUIRED PROGRAMS ARE AVAILABLE
-##
-## Run 'excom -help' to get a full list of options
-
-## Example. Find programs: ar tar bzip2. Exit if any one not found.
-# excom ar tar bzip2 || exit 1
-
-excom install  || exit 1
-
-
-$SRCROOT/mkmf
+# generate makefiles
+./mkmf
 
 ################################################################################
-# FINISH
+# finish
 echo "configuring done."
 
