cppdef: refactored

diff --git a/mk/cppdef b/mk/cppdef
--- a/mk/cppdef
+++ b/mk/cppdef
@@ -29,9 +29,9 @@
 # SWITCH TO MODERN SHELL IF POSSIBLE
 (test_exit_code_127_sdfjsdfksjdhfksjdhf  >/dev/null) 2>/dev/null
 if test $? -ne 127; then
-  if test -z "$CPPDEF_BASH_REDIRECTED"; then
-    CPPDEF_BASH_REDIRECTED=1
-    export CPPDEF_BASH_REDIRECTED
+  if test -z "$FORMAKE_BASH_REDIRECTED"; then
+    FORMAKE_BASH_REDIRECTED=1
+    export FORMAKE_BASH_REDIRECTED
     if test -x /bin/bash; then
       exec /bin/bash "$0" ${1+"$@"}
     elif test -x /usr/bin/bash; then
@@ -48,14 +48,22 @@ if test $? -ne 127; then
     fi
   fi
 fi
-CPPDEF_BASH_REDIRECTED=
-export CPPDEF_BASH_REDIRECTED
+FORMAKE_BASH_REDIRECTED=
+export FORMAKE_BASH_REDIRECTED
 ################################################################################
 
 script_name=`basename "$0"`
 test_dir=/tmp/cppdef_$$
 c_ext="c"
 orig_dir=`pwd`
+
+cd_param=
+(cd -P / >/dev/null) 2>/dev/null
+if test $? -eq 0; then
+  cd_param="-P"
+fi
+cd $cd_param $orig_dir
+
 
 print_help() {
 cat <<EOF
@@ -64,20 +72,21 @@ Read CPP defines
 Usage: $script_name [options] <defines>...
 
 Options:
- -c, -cc=<cmd>      specify compiler command
+ -cc=<cmd>          specify compiler command
  *.h|*.H|*.hpp      header files. Other file extensions are recognized
- -i, -inc=<list>    header files
- -v                 display version information and exit
+ -inc=<list>        header files
+ -cflags=<flags>    compiler flags
  -*                 compiler flags
- -                  disable interpretation of the following parameters and pass them as compiler flags
+ -v                 display version information and exit
+ -h|-help           print help
  <defines>..        preprocessor defines to read
 EOF
 }
 
 print_version() {
   cat <<EOF
-cppdef 1.1
-Copyright (C) 2015-2017 Oleksii Cherniavskyi
+cppdef 1.2
+Copyright (C) 2015-2018 Oleksii Cherniavskyi
 EOF
 }
 
@@ -88,115 +97,104 @@ clean_exit() {
   exit $ecode
 }
 
-probe_cc() {
-  check_cc_found=
-  ($op_cmd >/dev/null) 2>/dev/null
-  if test $? -ge 126; then
-    return
-  fi
-  check_cc_found=1
-
-  probe_out=/tmp/cc_probe_$$.txt
-  rm -f $probe_out
-  cc_cmd0=`echo "$op_cmd" | sed 's# [^/]*$##'`
-  ($cc_cmd0 -version >>$probe_out) 2>>$probe_out
-  ($cc_cmd0 --version >>$probe_out) 2>>$probe_out
-  ($cc_cmd0 -V >>$probe_out) 2>>$probe_out
-  ($cc_cmd0 -qversion >>$probe_out) 2>>$probe_out
-  ($cc_cmd0 -h >>$probe_out) 2>>$probe_out
-  ($cc_cmd0 --help >>$probe_out) 2>>$probe_out
-  ($cc_cmd0 >>$probe_out) 2>>$probe_out
-
-  if grep "Texas Instruments" $probe_out | grep "Tools Copyright" >/dev/null; then
-    op_cctype=ticc
-  elif grep -i mingw $probe_out >/dev/null; then
-    op_cctype=mingw
-  elif grep -i gcc $probe_out >/dev/null && grep -i "free software foundation" $probe_out >/dev/null; then
-    op_cctype=gcc
-  elif grep -i "clang version" $probe_out >/dev/null; then
-    op_cctype=clang
-  elif grep "tcc version" $probe_out >/dev/null; then
-    op_cctype=tinyc
-  elif grep -i "Sun C" $probe_out >/dev/null; then
-    op_cctype=sunpro
-  elif grep -i "IBM XL C" $probe_out >/dev/null; then
-    op_cctype=xlc
-  elif grep -i "MIPSpro Compilers" $probe_out >/dev/null; then
-    op_cctype=mipspro
-  elif grep -i microsoft $probe_out >/dev/null; then
-    op_cctype=msc
-  elif grep -i "PGI Compilers and Tools" $probe_out >/dev/null; then
-    op_cctype=pgi
-  elif grep "SDCC" $probe_out >/dev/null; then
-    op_cctype=sdcc
-  else
-    op_cctype=cc
-  fi
-  rm -f $probe_out
-}
-
-op_cmd=
 op_inc=
 op_cflags=
 op_def=
-pass_over=
 while test $# -gt 0; do
-  if test -z "$pass_over"; then
-    case `echo "$1" | sed 's/^\s*//'` in
-      "") : ;;
-      -)
-        pass_over=1
-        ;;
-      -h|-help|--help)
-        print_help
-        exit 0
-        ;;
-      -c|-cc=*)
-        test "$1" = "-c" && shift
-        arg=`echo " $1" | sed 's/^ -cc=//' | sed 's/^\s*//'`
-        if test -n "$arg"; then
-          op_cmd=`echo "$arg" | sed "s#^\(\.\.*\)/#$orig_dir/\1/#"`
-        fi
-        ;;
-      -i|-inc=*)
-        test "$1" = "-i" && shift
-        arg=`echo " $1" | sed 's/^ -inc=//' | sed 's/^\s*//'`
-        test -n "$arg" && op_inc="$op_inc $arg"
-        ;;
-      -v|--version)
-        print_version
-        exit 0
-        ;;
-      -*)
-        op_cflags="$op_cflags $1"
-        ;;
-      *.h)
-        op_inc="$op_inc $1"
-        ;;
-      *.H|*.[Hh]++|*.[Hh][Hh]|*.[Hh][Xx][Xx]|*.[Hh][Pp][Pp])
-        op_inc="$op_inc $1"
-        ;;
-      *)
-        op_def="$op_def $1"
-        ;;
-    esac
-  else
-    op_cflags="$op_cflags $1"
-  fi
+  case "$1" in
+    -h|-help)
+      print_help
+      exit 0
+      ;;
+    -v|--version)
+      print_version
+      exit 0
+      ;;
+    -cc=*)
+      arg=`echo "$1" | sed 's/^-cc=//'`
+      if test -n "$arg"; then
+        CONFIG_CC=`echo "$arg" | sed "s#^\(\.\.*\)/#$orig_dir/\1/#"`
+        export CONFIG_CC
+      fi
+      ;;
+    -inc=*)
+      arg=`echo "$1" | sed 's/^-inc=//'`
+      test -n "$arg" && op_inc="$op_inc $arg"
+      ;;
+    -cflags=*)
+      arg=`echo "$1" | sed 's/^-cflags=//'`
+      test -n "$arg" && op_cflags="$op_cflags $arg"
+      ;;
+    -*)
+      op_cflags="$op_cflags $1"
+      ;;
+    *.h|*.H|*.[Hh]++|*.[Hh][Hh]|*.[Hh][Xx][Xx]|*.[Hh][Pp][Pp])
+      op_inc="$op_inc $1"
+      ;;
+    *)
+      op_def="$op_def $1"
+      ;;
+  esac
   shift
 done
 
-test -z "$op_def" && exit 0
-test -z "$op_cmd" && op_cmd=gcc
+if test -n "$op_cflags"; then 
+  CONFIG_CFLAGS=$op_cflags
+  export CONFIG_CFLAGS
+fi
 
-probe_cc
-if test x$check_cc_found = x; then
-  echo "$script_name: compiler not found: $op_cmd" >&2
+test -z "$op_def" && exit 0
+
+################################################################################
+#CONFIG_MK_PATH
+if test -z "$CONFIG_MK_PATH"; then
+  cd $cd_param `dirname "$0"`
+  if test -x $script_name; then
+    CONFIG_MK_PATH=`pwd`
+  elif test -d $CONFIG_SRCROOT/mk && test -x $CONFIG_SRCROOT/mk/$script_name; then
+    cd $cd_param $CONFIG_SRCROOT/mk
+    CONFIG_MK_PATH=`pwd`
+  else
+    IFS_save=$IFS
+    IFS=:
+    for dir in $PATH; do
+      if test -f "$dir/$script_name" && test -x "$dir/$script_name" ; then
+        abs_path "$dir"
+        CONFIG_MK_PATH=$abs_path_ret
+        break
+      fi
+    done
+    IFS=$IFS_save
+  fi
+
+  if test -z "$CONFIG_MK_PATH"; then
+    echo "$script_name: Formake modules not found" >&2
+    exit 1
+  fi
+
+  export CONFIG_MK_PATH
+  PATH="$CONFIG_MK_PATH:$PATH"
+  export PATH
+  cd $cd_param $orig_dir
+fi
+################################################################################
+
+if test -f $CONFIG_MK_PATH/subscript; then
+  . $CONFIG_MK_PATH/subscript
+else
+  echo "$script_name: module not found: subscript" >&2
+  exit 1
+fi
+
+formake_cprobe
+
+if test -z "$CONFIG_CC"; then
+  echo "$script_name: compiler not found" >&2
   exit 1
 fi
 
 cpp_flag=-E
-case "$op_cctype" in
+case "$CONFIG_CC_TYPE" in
   ticc)
     cpp_flag=-ppl
     ;;
@@ -208,7 +206,7 @@ esac
 rm -rf $test_dir 2>/dev/null
 (mkdir $test_dir >/dev/null) 2>/dev/null
 if test ! -d $test_dir; then
-  echo "$script_name: error: could not create temporary directory $test_dir" >&2
+  echo "$script_name: could not create temporary directory $test_dir" >&2
   exit 1
 fi
 cd $test_dir
@@ -238,7 +236,7 @@ CPPDEF_DEFVAL=$def
 #endif
 EOF
   if test "$op_cctype" = ticc; then
-    $op_cmd $op_cflags $cpp_flag $test_src 2>/dev/null
+    $CONFIG_CC $CONFIG_CFLAGS $cpp_flag $test_src 2>/dev/null
     if test $? != 0; then
       echo "$script_name: CPP error" >&2
       clean_exit 1
@@ -246,7 +244,7 @@ EOF
     cat $test_pp > test_c.out
     rm -f $test_pp
   else
-    $op_cmd $op_cflags $cpp_flag $test_src 2>/dev/null > test_c.out
+    $CONFIG_CC $CONFIG_CFLAGS $cpp_flag $test_src 2>/dev/null > test_c.out
     if test $? != 0; then
       echo "$script_name: CPP error" >&2
       clean_exit 1
@@ -254,13 +252,7 @@ EOF
   fi
 
   defval=`cat test_c.out | grep "^ *CPPDEF_DEFVAL" | sed 's/^ *CPPDEF_DEFVAL=//' | sed 's/ *$//' | sed 's/"$//' |  sed 's/^"//' | tr -d '\n'`
-  if test -n "$defval"; then
-    if test -n "$defvals"; then
-      defvals="$defvals $defval"
-    else
-      defvals=$defval
-    fi
-  fi
+  defvals="$defvals $defval"
 done
 
 echo "$defvals" | sed 's/^ *//'
