canonical interpretation of global CONFIG_ variables and parameters. Other improvements and fixes

diff --git a/mk/cprobe b/mk/cprobe
--- a/mk/cprobe
+++ b/mk/cprobe
@@ -115,7 +115,6 @@ test_dir=/tmp/cprobe_$$
 cc_is_cross=0
 headers=$test_dir/cprobe_inc_headers
 cc_macros_loaded=
-CC=$CONFIG_CC
 
 print_help() {
 cat <<EOF
@@ -125,6 +124,7 @@ Usage: $script_name [cmd] [options]
 
 Options:
  cmd           optional 1st parameter specifies compiler command
+ -c++          C++ mode
  -t, -type     get compiler type
  -r, -ver      get compiler version
  -c, -cmd      get compiler command
@@ -259,8 +259,8 @@ EOF
 
 print_version() {
   cat <<EOF
-cprobe 1.4
-Copyright (C) 2015-2017 Oleksii Cherniavskyi
+cprobe 1.5
+Copyright (C) 2015-2018 Oleksii Cherniavskyi
 EOF
 }
 
@@ -458,19 +458,19 @@ load_cc_macros() {
   fi
   cat $script_abs | sed -n -e '/\* COMPILER DEFINES \*/,$p' | grep -v "^EOF" >> $probe_h
   if test $cmd_type = ticc; then
-    $prop_cmd $CONFIG_CFLAGS $CPP_FLAG $probe_h 2>/dev/null
+    $prop_cmd $CPROBE_CFLAGS $CPP_FLAG $probe_h 2>/dev/null
     cat $probe_pp > $probe_h_out
     if test x$check_cxx_ok = x1; then
       rm -f $probe_pp
       cat $probe_h > $probe_hxx
-      $prop_cmd $CONFIG_CFLAGS $CPP_FLAG $probe_hxx 2>/dev/null
+      $prop_cmd $CPROBE_CFLAGS $CPP_FLAG $probe_hxx 2>/dev/null
       cat $probe_pp >> $probe_h_out
     fi
   else
-    $prop_cmd $CONFIG_CFLAGS $CPP_FLAG $probe_h 2>/dev/null > $probe_h_out
+    $prop_cmd $CPROBE_CFLAGS $CPP_FLAG $probe_h 2>/dev/null > $probe_h_out
     if test x$check_cxx_ok = x1; then
       cat $probe_h > $probe_hxx
-      $prop_cmd $CONFIG_CFLAGS $CPP_FLAG $probe_hxx 2>/dev/null >> $probe_h_out
+      $prop_cmd $CPROBE_CFLAGS $CPP_FLAG $probe_hxx 2>/dev/null >> $probe_h_out
     fi
   fi
   cat $probe_h_out | grep "^D[SV][EA][TL]" | sed 's/= */=/' | sed 's/ *$//' | sed 's/=\(.*\)$/="\1"/' | sed 's/""*/"/g' | sed 's/ *= */=/' | sed 's/="*$/=/' | sed 's///' > $probe_sh
@@ -985,7 +985,7 @@ int main(int argc, char *argv[])
 }
 
 EOF
-    $prop_cmd $CONFIG_CFLAGS $o_exe_flag $dm_exe $dm_src 2>/dev/null 1>&2
+    $prop_cmd $CPROBE_CFLAGS $o_exe_flag $dm_exe $dm_src 2>/dev/null 1>&2
     prop_data_model=`./$dm_exe`
     rm -f $dm_src $dm_exe
   fi
@@ -1128,7 +1128,7 @@ int main(int argc, char *argv[])
 }
 
 EOF
-    $prop_cmd $CONFIG_CFLAGS $o_exe_flag $border_exe $border_src 2>/dev/null 1>&2
+    $prop_cmd $CPROBE_CFLAGS $o_exe_flag $border_exe $border_src 2>/dev/null 1>&2
     prop_endianness=`./$border_exe`
     rm -f $border_src $border_exe
   fi
@@ -1244,16 +1244,32 @@ get_cc_list() {
 
   case "x$config_os" in
     xmacos)
-      cc_list="clang gcc c99 cc c89 clang++ g++ c++ CC"
+      if test x$CPROBE_LANG = "xc++"; then
+        cc_list="clang++ g++ c++ CC"
+      else
+        cc_list="clang gcc c99 cc c89 clang++ g++ c++ CC"
+      fi
       ;;
     xaix)
-      cc_list="xlc gcc clang c99 cc c89 xlc++ xlC g++ clang++ c++ CC"
+      if test x$CPROBE_LANG = "xc++"; then
+        cc_list="xlc++ xlC g++ clang++ c++ CC"
+      else
+        cc_list="xlc gcc clang c99 cc c89 xlc++ xlC g++ clang++ c++ CC"
+      fi
       ;;
     xcygwin | xmsys | xmks)
-      cc_list="gcc clang cl.exe c99 cc c89 g++ clang++ c++ CC"
+      if test x$CPROBE_LANG = "xc++"; then
+        cc_list="cl.exe g++ clang++ c++ CC"
+      else
+        cc_list="gcc clang cl.exe c99 cc c89 g++ clang++ c++ CC"
+      fi
       ;;
     *)
-      cc_list="gcc clang c99 cc c89 g++ clang++ c++ CC"
+      if test x$CPROBE_LANG = "xc++"; then
+        cc_list="g++ clang++ c++ CC"
+      else
+        cc_list="gcc clang c99 cc c89 g++ clang++ c++ CC"
+      fi
       ;;
   esac
 }
@@ -1264,7 +1280,7 @@ probe_base() {
   prop_cflags=
   probe_cc_ok=
   probe_cflags_ok=
-  if test -z "$CC"; then
+  if test -z "$CPROBE_CC"; then
     get_cc_list
 
     for prop_cmd in $cc_list; do
@@ -1277,7 +1293,7 @@ probe_base() {
       prop_cmd=
     fi
   else
-    prop_cmd=$CC
+    prop_cmd=$CPROBE_CC
     check_cc
   fi
 
@@ -1286,8 +1302,8 @@ probe_base() {
   fi
   probe_cc_ok=1
 
-  if test -n "$CONFIG_CFLAGS"; then
-    prop_cflags=$CONFIG_CFLAGS
+  if test -n "$CPROBE_CFLAGS"; then
+    prop_cflags=$CPROBE_CFLAGS
     check_cc
     if test x$check_cc_ok != x1; then
       return
@@ -1317,14 +1333,14 @@ probe_ext() {
 
   if test x$probe_base_ok != x1; then
     if test x$probe_cc_ok != x1; then
-      if test -n "$CC" && test x$check_cc_found = x1; then
-        printf "%s\n" "${script_name}: invalid compiler: $CC" >&2
+      if test -n "$CPROBE_CC" && test x$check_cc_found = x1; then
+        printf "%s\n" "${script_name}: invalid compiler: $CPROBE_CC" >&2
       else
-        test -n "$CC" && cc_list=$CC
+        test -n "$CPROBE_CC" && cc_list=$CPROBE_CC
         printf "%s\n" "${script_name}: compiler not found: $cc_list" >&2
       fi
     elif test x$probe_cflags_ok != x1; then
-      printf "%s\n" "${script_name}: invalid compiler flags: $CONFIG_CFLAGS" >&2
+      printf "%s\n" "${script_name}: invalid compiler flags: $CPROBE_CFLAGS" >&2
     fi
     return
   fi
@@ -1362,6 +1378,9 @@ while test $# -gt 0; do
       -v|--version)
         print_version
         exit 0
+        ;;
+      -c++)
+        CPROBE_LANG="c++"
         ;;
       -t|-type)
         print_string="$print_string type"
@@ -1416,7 +1435,7 @@ while test $# -gt 0; do
         ;;
       *)
         if test x$param1 = x1; then
-          CC=`echo "$1" | sed "s#^\(\.\.*\)/#$orig_dir/\1/#"`
+          op_cc=`echo "$1" | sed "s#^\(\.\.*\)/#$orig_dir/\1/#"`
         else
           op_cflags="$op_cflags $1"
         fi
@@ -1428,9 +1447,36 @@ while test $# -gt 0; do
   shift
   param1=
 done
-if test -n "$op_cflags"; then
-  CONFIG_CFLAGS=$op_cflags
+
+#################
+if test -n "$op_cc"; then
+  if test "$CPROBE_LANG" = "c++"; then
+    CONFIG_CXX=$op_cc
+    export CONFIG_CXX
+  else
+    CONFIG_CC=$op_cc
+    export CONFIG_CC
+  fi
 fi
+
+if test -n "$op_cflags"; then 
+  if test "$CPROBE_LANG" = "c++"; then
+    CONFIG_CXXFLAGS=$op_cflags
+    export CONFIG_CXXFLAGS
+  else
+    CONFIG_CFLAGS=$op_cflags
+    export CONFIG_CFLAGS
+  fi
+fi
+
+if test "$CPROBE_LANG" = "c++"; then
+  CPROBE_CC=$CONFIG_CXX
+  CPROBE_CFLAGS=$CONFIG_CXXFLAGS
+else
+  CPROBE_CC=$CONFIG_CC
+  CPROBE_CFLAGS=$CONFIG_CFLAGS
+fi
+#################
 
 rm -rf $test_dir 2>/dev/null
 (mkdir $test_dir >/dev/null) 2>/dev/null
diff --git a/mk/mkmf b/mk/mkmf
--- a/mk/mkmf
+++ b/mk/mkmf
@@ -62,6 +62,8 @@ default_static_dir="_static"
 default_pic_dir="_pic"
 tmp_file=_mkmf_out_buffer_093471848
 all_sources=
+have_c=
+have_cxx=
 
 cd_param=
 (cd -P / >/dev/null) 2>/dev/null
@@ -325,9 +327,11 @@ add_mkmf_data() {
       case "$src" in
         *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
           eval target_${prefix}_have_cxx=1
+          have_cxx=1
           ;;
         *.c)
           eval target_${prefix}_have_c=1
+          have_c=1
           ;;
         *)
           echo "$script_name: error: unknown source file type: $src" >&2
@@ -595,9 +599,11 @@ while test $# -gt 0; do
           case "$1" in
             *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
               target___have_cxx=1
+              have_cxx=1
               ;;
             *.c)
               target___have_c=1
+              have_c=1
               ;;
             *)
               echo "$script_name: error: bad source type $1" >&2
@@ -711,33 +717,6 @@ done
 prefix_list="$prefix_list $prefix_add"
 
 ################################################################################
-#CONFIG_SRCROOT
-if test -z "$CONFIG_SRCROOT"; then
-  while test `pwd` != '/'; do
-    if test -d mk && test -x mk/$script_name; then
-      CONFIG_SRCROOT=`pwd`
-      break
-    fi
-    cd $cd_param ..
-  done
-  cd $cd_param $op_srcdir
-
-  if test -z "$CONFIG_SRCROOT"; then
-    CONFIG_SRCROOT=`pwd`
-    mkmf_num=`ls *.mkmf 2>/dev/null | wc -l`
-    while test $mkmf_num -ge 1; do
-      CONFIG_SRCROOT=`pwd`
-      test `pwd` = '/' && break
-      cd $cd_param ..
-      mkmf_num=`ls *.mkmf 2>/dev/null | wc -l`
-    done
-    cd $cd_param $op_srcdir
-  fi
-  export CONFIG_SRCROOT
-fi
-
-
-################################################################################
 #CONFIG_MK_PATH
 if test -z "$CONFIG_MK_PATH"; then
   cd $cd_param `dirname "$0"`
@@ -760,7 +739,7 @@ if test -z "$CONFIG_MK_PATH"; then
   fi
 
   if test -z "$CONFIG_MK_PATH"; then
-    echo "$script_name: error: Formake modules not found"
+    echo "$script_name: Formake modules not found" >&2
     exit 1
   fi
 
@@ -769,9 +748,26 @@ if test -z "$CONFIG_MK_PATH"; then
   export PATH
   cd $cd_param $op_srcdir
 fi
-
-
 ################################################################################
+
+if test -f $CONFIG_MK_PATH/subscript; then
+  . $CONFIG_MK_PATH/subscript
+else
+  echo "$script_name: module not found: subscript" >&2
+  exit 1
+fi
+
+formake_config_srcroot
+
+if test x$have_c = x1; then
+  formake_cprobe
+fi
+if test x$have_cxx = x1; then
+  formake_cxxprobe
+fi
+
+#####################
+
 if test x$op_print = x1; then
   rm -f $tmp_file
   op_out_mkfile=$tmp_file
diff --git a/mk/subscript b/mk/subscript
--- a/mk/subscript
+++ b/mk/subscript
@@ -62,7 +62,6 @@ formake_config_mk_path() {
   fi
 }
 
-
 formake_cprobe() {
   if test x$FORMAKE_CPROBE_RUN = x1; then
     return
@@ -112,6 +111,83 @@ formake_cprobe() {
     export CONFIG_CC_SUS
   else
     echo "$formake_script_name: subscript: cprobe not found" >&2
+    exit 1
+  fi
+}
+
+formake_cprobe_exifer() {
+  formake_cprobe
+  if test -z "$CONFIG_CC"; then
+    echo "$formake_script_name: compiler not found" >&2
+    exit 1
+  fi
+  if test -z "$CONFIG_CC_TYPE"; then
+    echo "$formake_script_name: unsupported compiler type: $CONFIG_CC" >&2
+    exit 1
+  fi
+}
+
+formake_cxxprobe() {
+  if test x$FORMAKE_CXXPROBE_RUN = x1; then
+    return
+  fi
+  FORMAKE_CXXPROBE_RUN=1
+  export FORMAKE_CXXPROBE_RUN
+  
+  formake_config_mk_path
+
+  if cmdok -f cprobe; then
+    formake_out_buf=/tmp/formake_out_buf_$$
+    CPROBE_LANG="c++" cprobe -1 > $formake_out_buf
+    . $formake_out_buf
+    rm -f $formake_out_buf
+    
+    
+    CONFIG_CXX=$CC_CMD
+    CONFIG_CXX_TYPE=$CC_TYPE
+    CONFIG_CXX_VERSION=$CC_VERSION
+    CONFIG_CXX_STD=$CC_CXX_STD
+    CONFIG_CXX_CC_STD=$CC_STD
+    CONFIG_CXX_OS=$CC_OS
+    CONFIG_CXX_OS_VERSION=$CC_OS_VERSION
+    CONFIG_CXX_ARCH=$CC_ARCH
+    CONFIG_CXX_BITNESS=$CC_BITNESS
+    CONFIG_CXX_ENDIANNESS=$CC_ENDIANNESS
+    CONFIG_CXX_DATA_MODEL=$CC_DATA_MODEL
+    CONFIG_CXX_FLAG_CROSS=$CC_FLAG_CROSS
+    CONFIG_CXX_FLAG_CXX=$CC_FLAG_CXX
+    CONFIG_CXX_POSIX=$CC_POSIX
+    CONFIG_CXX_SUS=$CC_SUS
+  
+    export CONFIG_CXX
+    export CONFIG_CXX_TYPE
+    export CONFIG_CXX_VERSION
+    export CONFIG_CXX_STD
+    export CONFIG_CXX_CC_STD
+    export CONFIG_CXX_OS
+    export CONFIG_CXX_OS_VERSION
+    export CONFIG_CXX_ARCH
+    export CONFIG_CXX_BITNESS
+    export CONFIG_CXX_ENDIANNESS
+    export CONFIG_CXX_DATA_MODEL
+    export CONFIG_CXX_FLAG_CROSS
+    export CONFIG_CXX_FLAG_CXX
+    export CONFIG_CXX_POSIX
+    export CONFIG_CXX_SUS
+  else
+    echo "$formake_script_name: subscript: cprobe not found" >&2
+    exit 1
+  fi
+}
+
+formake_cxxprobe_exifer() {
+  formake_cxxprobe
+  if test -z "$CONFIG_CXX"; then
+    echo "$formake_script_name: compiler not found" >&2
+    exit 1
+  fi
+  if test -z "$CONFIG_CXX_TYPE"; then
+    echo "$formake_script_name: unsupported compiler type: $CONFIG_CXX" >&2
     exit 1
   fi
 }
