many changes, fixes for alpha version

diff --git a/formake/mkrule b/formake/mkrule
--- a/formake/mkrule
+++ b/formake/mkrule
@@ -130,7 +130,8 @@ print_install_help() {
 $script_name install TYPE [OPTIONS] FILE..
   TYPE             files type: bin, sbin, libexec, lib, inc, share, man[1-8], doc, etc
   -t TARGET        specify phony target that start generated rules
-  -path PATH       installation path
+  -rename NAME     set destination file name
+  -d DIR           installation directory
   FILE..           files to install. RC files are accepted
 EOF
 }
@@ -477,10 +478,11 @@ EOF
     if test -z "$op_install_path"; then
       op_install_path=$BINDIR
     fi
+    file_base=`basename $app_local`
     cat <<EOF
 install: install-$op_name
 install-$op_name: $app_local
-	$INSTALL -m 0755 $app_local $op_install_path
+	$INSTALL -m 0755 -D $app_local $op_install_path/$file_base
 EOF
   fi
 
@@ -648,10 +650,11 @@ install: install-$op_name
 install-$op_name: $lib_targets
 EOF
     for file in $lib_regular; do
+      file_base=`basename $file`
       if test x$op_shared = x1; then
-	    echo "	$INSTALL -m 0755 $file $op_install_path"
+	    echo "	$INSTALL -m 0755 -D $file $op_install_path/$file_base"
       else
-	    echo "	$INSTALL -m 0644 $file $op_install_path"
+	    echo "	$INSTALL -m 0644 -D $file $op_install_path/$file_base"
       fi
     done
     for file in $lib_symbolic; do
@@ -790,18 +793,16 @@ mkinstall() {
     exit 1
   fi
 
+  num_files=`echo "$op_files" | wc -w`
+  if test -n "$op_rename" && test $num_files -gt 1; then
+    echo "$script_name: option '-rename' can't be used for multiple installation files" >&2
+    exit 1
+  fi
+
   if test -z "$op_target"; then
     get_random
     op_target="install-$op_type-$RANDOM"
   fi
-  case $op_type in
-    man*)
-      target_base="install-man"
-      ;;
-    *)
-      target_base="install-$op_type"
-      ;;
-  esac
 
   case $op_type in
     bin)
@@ -843,7 +844,7 @@ mkinstall() {
       ;;
   esac
 
-  test -z "$op_install_path" || dir=$op_install_path
+  test -z "$op_dir" || dir=$op_dir
 
   cat <<EOF
 ################################################################################
@@ -853,12 +854,16 @@ EOF
 
   cat <<EOF
 install: $op_target
-$target_base: $op_target
 $op_target: $op_files
 EOF
-  for file in $op_files; do
-    printf "\t%s\n" "install -m $perm $file $dir"
-  done
+  if test -n "$op_rename"; then
+    printf "\t%s\n" "$INSTALL -m $perm -D $op_files $dir/$op_rename"
+  else
+    for file in $op_files; do
+      file_base=`basename $file`
+      printf "\t%s\n" "$INSTALL -m $perm -D $file $dir/$file_base"
+    done
+  fi
   echo ""
 }
 
@@ -1014,7 +1019,7 @@ while test $# -gt 0; do
       ;;
     -d)
       case $op_mode in
-        obj|app|lib|subdir)
+        obj|app|lib|subdir|install)
           : ;;
         *)
           echo "$script_name: error: invalid parameter $1 for current mode" >&2
@@ -1254,17 +1259,17 @@ while test $# -gt 0; do
       op_distclean=1
       current_opt=
       ;;
-    -path)
+    -rename)
       if test $op_mode != install; then
         echo "$script_name: error: invalid parameter $1 for current mode" >&2
         exit 1
       fi
       shift
       if test -z "$1"; then
-        echo "$script_name: error: parameter -path requires argument" >&2
+        echo "$script_name: error: parameter -rename requires argument" >&2
         exit 1
       fi
-      op_install_path=$1
+      op_rename=$1
       current_opt=
       ;;
     -prefix=*)
@@ -1479,8 +1484,9 @@ case $op_mode in
 # ALL
 # $script_name $script_options
 all:
-install: all
+install:
 clean:
+distclean:
 
 EOF
     ;;
diff --git a/src/confighelp/confighelp b/src/confighelp/confighelp
--- a/src/confighelp/confighelp
+++ b/src/confighelp/confighelp
@@ -1,4 +1,7 @@
 #!/bin/sh
+#
+# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
+#
 
 SCRIPT_NAME=`basename $0`
 
@@ -30,7 +33,7 @@ for param in "$@"; do
       op_install=1
       ;;
     *)
-      echo "$SCRIPT_NAME: subscript error: invalid parameter: $param"
+      echo "$SCRIPT_NAME: error: invalid parameter: $param" >&2
       exit 1
       ;;
   esac
diff --git a/src/cstem/test/cstem+ b/src/cstem/test/cstem+
--- a/src/cstem/test/cstem+
+++ b/src/cstem/test/cstem+
@@ -35,6 +35,7 @@ orig_dir=`pwd`
 abs_path $0
 script_abs=$abs_path_ret
 script_dir=`dirname $script_abs`
+out_format=1
 config_file="$script_dir/cstem+.conf"
 PATH="$script_dir:$PATH"
 
@@ -63,9 +64,10 @@ cat <<EOF
 Configure and probe C++ compiler
 
 $script_name [options]
-$script_name config [CMD [FLAGS]] [-cflags FLAGS]
+$script_name config [-cc=CMD] [-cflags=FLAGS]
+$script_name probe [-cc=CMD] [-cflags=FLAGS]
 
-Options:
+By default $script_name prints information about configured compiler
  -id            get compiler id
  -ver           get compiler version
  -cmd           get compiler command
@@ -79,9 +81,17 @@ Options:
  -endian        get target endianess
  -dm            get target data model
 
-Optional config parameters:
- CMD [FLAGS]    specify compiler command with optional flags
- -cflags FLAGS  specify compiler flags
+
+Config mode. Probe compiler and generate config file
+ -cc=CMD        specify compiler command with optional flags
+ -cflags=FLAGS  specify compiler flags
+
+Probe mode. Probe compiler and print information to a standard output
+ -cc=CMD        specify compiler command with optional flags
+ -cflags=FLAGS  specify compiler flags
+ -f1            print in format 1 (default): VAR="VALUE"
+ -f2            print in format 2: FIELD: VALUE
+ -f3            print in format 3: VALUE
 EOF
 }
 
@@ -824,7 +834,9 @@ read_cc_props() {
 }
 
 perform_probe() {
-  rm -f $config_file
+  if test x$mode_config = x1; then
+    rm -f $config_file
+  fi
 
   if test -z "$probe_cc_cmd"; then
     if test x$have_pofig = x1; then
@@ -858,17 +870,36 @@ perform_probe() {
   fi
 
   if test x$cc_is_ok = x1; then
-    printf "%s\n" "${script_name}: found C++ compiler $cc_cmd" >&2
+    if test x$mode_config = x1; then
+      printf "%s\n" "found C++ compiler $cc_cmd" >&2
+    fi
     read_cc_props
     config_cmd=$cc_cmd
     for config in $config_list; do
       config_var=`echo "CC_${config}" | tr [a-z] [A-Z]`
       eval config_val=\$config_$config
-      printf "%s\n" "$config_var=\"$config_val\"" >>$config_file
+      if test x$mode_config = x1; then
+        printf "%s\n" "$config_var=\"$config_val\"" >>$config_file
+      else
+        case $out_format in
+          1)
+            printf "%s\n" "$config_var=\"$config_val\""
+            ;;
+          2) 
+            printf "%s\n" "$config_var: $config_val"
+            ;;
+          3) 
+            printf "%s\n" "${config_val:--}"
+            ;;
+        esac
+      fi
       eval $config_var=\$config_val
     done
   else
-    printf "%s\n" "${script_name}: C++ compiler not found" >&2
+    if test x$mode_config = x1; then
+      printf "%s\n" "${script_name}: C++ compiler not found" >&2
+    fi
+    exit 1
   fi
 }
 
@@ -882,35 +913,34 @@ case x"$1" in
     mode_config=1
     shift
     ;;
+  xprobe)
+    mode_probe=1
+    shift
+    ;;
   *)
     mode_info=1
     ;;
 esac
 
-if test x$mode_config = x1; then
-  current_opt=cmd_start
+if test x$mode_config$mode_probe = x1; then
   while test $# -gt 0; do
     case "$1" in
-      -cflags)
-        current_opt=cflags_start
+      -cc=*)
+        probe_cc_cmd=`echo -n "$1" | sed 's/^[^=]*=//'`
+        ;;
+      -cflags=*)
+        probe_cc_flags=`echo -n "$1" | sed 's/^[^=]*=//'`
+        ;;
+      -f1|-f2|-f3)
+        if test x$mode_probe = x; then
+          printf "%s\n" "$script_name: invalid parameter $1" >&2
+          exit 1
+        fi
+        out_format=`echo -n "$1" | sed 's/^-f//'`
         ;;
       *)
-        case $current_opt in
-          cmd_start)
-            probe_cc_cmd=$1
-            current_opt=cmd
-            ;;
-          cmd)
-            probe_cc_cmd="$probe_cc_cmd $1"
-            ;;
-          cflags_start)
-            probe_cc_flags=$1
-            current_opt=cflags
-            ;;
-          cflags)
-            probe_cc_flags="$probe_cc_flags $1"
-            ;;
-        esac
+        printf "%s\n" "$script_name: invalid parameter $1" >&2
+        exit 1
         ;;
     esac
     shift
@@ -964,11 +994,11 @@ elif test x$mode_info = x1; then
   done
 fi
 
-if test ! -f $config_file; then
+if test x$mode_info = x1 && test ! -f $config_file; then
   mode_config=1
 fi
 
-if test x$mode_config = x1; then
+if test x$mode_config$mode_probe = x1; then
   perform_probe
 else
   . $config_file
diff --git a/src/iflib/iflib b/src/iflib/iflib
--- a/src/iflib/iflib
+++ b/src/iflib/iflib
@@ -4,28 +4,53 @@
 #
 
 abs_path() {
-  arg=$1
-  if test -e "$arg"; then
-    if test -d $arg; then
-      file=
+  _sub_orig_dir=`pwd`
+  if test $# = 0; then
+    abs_path_ret=
+    return
+  fi
+  if test $# = 2; then
+    _arg_orig_dir=$1
+    _arg=$2
+    if echo -n "$_arg" | grep "^/" > /dev/null; then
+      :
     else
-      file=`basename -- $arg`
-      arg=`dirname -- $arg`
+      _arg=`echo -n "$_arg_orig_dir/$_arg" | sed 's!//*!/!g'`
     fi
-
-    cd $arg
-    abs_path_ret=`pwd`
-    if test x"$file" != "x"; then
-      abs_path_ret="$abs_path_ret/$file"
-    fi
-
-    cd $orig_dir
   else
-    if echo -n "$arg" | grep "^/" > /dev/null; then
-      abs_path_ret="$arg"
+    _arg=$1
+  fi
+  if test -e "$_arg"; then
+    if test -d $_arg; then
+      _file=
     else
-      abs_path_ret="$orig_dir/$arg"
+      _file=`basename -- $_arg`
+      _arg=`dirname -- $_arg`
     fi
+
+    cd $_cd_param $_arg
+    abs_path_ret=`pwd`
+    if test x"$_file" != "x"; then
+      abs_path_ret="$abs_path_ret/$_file"
+    fi
+
+    cd $_cd_param $_sub_orig_dir
+  else
+    if echo -n "$_arg" | grep "^/" > /dev/null; then
+      abs_path_ret="$_arg"
+    else
+      abs_path_ret="$_sub_orig_dir/$_arg"
+    fi
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#//*#/#g'`
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/*$#/#'`
+    string_prev=
+    while test "x$abs_path_ret" != "x$string_prev" ; do
+      string_prev=$abs_path_ret
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/[^/][^/][^/][^/]*/\.\./#/#g' | sed 's#/[^/][^/.]/\.\./#/#g' | sed 's#/[^/.][^/]/\.\./#/#g' | sed 's#/[^/.]/\.\./#/#g'`
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#^/\.\./#/#' | sed 's#^/\.\.$#/#'`
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/\./#/#g' | sed 's#/\.$#/#'`
+    done
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/$##' | sed 's#^$#/#'`
   fi
 }
 
@@ -575,7 +600,7 @@ EOF
       def_name=`echo -n "$def_string" | sed 's/[^a-zA-Z0-9_].*//'`
       inv_chars=`echo -n "$def_name" | sed 's/[_a-zA-Z0-9]//g'`
       if test -n "$inv_chars" || echo -n "$def_name" | grep "^[0-9]" > /dev/null; then
-        echo "$script_name: error invalid macro $def_name"
+        echo "$script_name: error invalid macro $def_name" >&2
         exit 1
       fi
       rpart=`echo -n "$def_string" | sed 's/[a-zA-Z0-9_]*//'`
@@ -597,7 +622,7 @@ EOF
             opstr="=="
             ;;
           *)
-            echo "$script_name: error invalid argument $def_string"
+            echo "$script_name: error invalid argument $def_string" >&2
             exit 1
             ;;
         esac
@@ -793,19 +818,21 @@ fi
 # CHECKING SOURCE FILES
 if test -n "$op_src"; then
   for src in $op_src; do
-    if echo -n "$src" | grep "^/" > /dev/null; then : ; else
-      src="$orig_dir/$src"
+    if echo -n "$src" | grep "^/" > /dev/null; then 
+      src_full=$src
+    else
+      src_full="$orig_dir/$src"
     fi
 
     echo_status "%s" "checking source file $src ... "
 
-    if test ! -f $src; then
+    if test ! -f $src_full; then
       echo_status "%s\n" "Failed"
       echo_status "%s\n" "  file $src not found"
       script_exit 1
     fi
-    cp $src .
-    src_base=`basename $src`
+    cp $src_full .
+    src_base=`basename $src_full`
 
     echo "\$ $CC_CMD -c -o test.o $src_base" >> iflib.log
     $CC_CMD -c -o test.o $src_base >> iflib.log 2>&1
diff --git a/src/mkconfigure/test/mkconfigure b/src/mkconfigure/test/mkconfigure
--- a/src/mkconfigure/test/mkconfigure
+++ b/src/mkconfigure/test/mkconfigure
@@ -12,12 +12,14 @@ rm -f $tmp_help
 op_pkgname=softmodule
 op_pkgver=
 out_file=configure
+out_file_dir=.
 rm_out_file=0
 
 print_help() {
   cat <<EOF
 $script_name [options]
- -v             print version
+ -name NAME     package name (PACKAGE_NAME) [$op_pkgname]
+ -ver VERSION   package version (PACKAGE_VERSION)
  -o FILE        output script file [$out_file]
  -params=".."   list of parameters for parsing
  -pofig         probe a system with pofig test tool
@@ -26,12 +28,11 @@ $script_name [options]
  -cstem         configure/probe C compiler with cstem tool
  -cstem+        configure/probe C++ compiler with cstem+ tool
  -sh CODE       insert shell string
- -name NAME     package name (PACKAGE_NAME) [$op_pkgname]
- -ver VERSION   package version (PACKAGE_VERSION)
  -build-h       generate BUILDROOT/build.h config header
  -no-install    disable installation parameters
  -no-vpath      disable VPATH feature
  -mkpackage     create package
+ -v             print version
 EOF
 }
 
@@ -156,7 +157,7 @@ while test $# -gt 0; do
       fi
       out_file_dir=`dirname "$out_file"`
       if test ! -d "$out_file_dir"; then
-        echo "$script_name: error. Directory not found: $out_file_dir"
+        echo "$script_name: error. Directory not found: $out_file_dir" >&2
         clean_exit 1
       fi
       current_opt=
@@ -173,10 +174,10 @@ while test $# -gt 0; do
   shift
 done
 
+
 if test $op_iflib:$op_cstemx:$op_cstem = 1::; then
   op_cstem=1
 fi
-
 
 formake_scripts=
 if test x$op_no_install = x; then
@@ -194,8 +195,22 @@ fi
 if test x$op_iflib = x1; then
   formake_scripts="$formake_scripts iflib"
 fi
-formake_scripts="$formake_scripts mkrule"
 formake_scripts=`echo -n "$formake_scripts" | sed 's/^ *//'`
+
+if test x$op_mkpackage = x1; then
+  if mkpackage -h >/dev/null; then
+    :
+  else
+    echo "$script_name: mkpackage script not found" >&2
+    clean_exit 1
+  fi
+  test -d $out_file_dir/formake || mkdir -p $out_file_dir/formake
+  if test ! -d $out_file_dir/formake; then
+    echo "$script_name: could not create Formake directory $out_file_dir/formake" >&2
+    clean_exit 1
+  fi
+  mkpackage -d $out_file_dir/formake -std $formake_scripts mkbuildroot abspath relpath listed mkrule || clean_exit 1
+fi
 
 
 cat <<TOP_EOF >$out_file
@@ -229,20 +244,20 @@ TOP_EOF
 fi
 if test x$op_cstem$op_cstemx = x11; then
   cat <<"TOP_EOF" >>$out_file
-C_OPTIONS="-cc -cflags -ldflags -c-ldflags"
-CXX_OPTIONS="-cxx -cxxflags -ldflags -cxx-ldflags"
+C_OPTIONS="-cc -cflags -ldflags -c-ldflags CC CFLAGS LDFLAGS C_LDFLAGS"
+CXX_OPTIONS="-cxx -cxxflags -ldflags -cxx-ldflags CXX CXXFLAGS LDFLAGS CXX_LDFLAGS"
 TOP_EOF
   validate_ops="$validate_ops \$C_OPTIONS \$CXX_OPTIONS"
   config_help_ops="$config_help_ops -cc -cxx"
 elif test x$op_cstem = x1; then
   cat <<"TOP_EOF" >>$out_file
-C_OPTIONS="-cc -cflags -ldflags"
+C_OPTIONS="-cc -cflags -ldflags CC CFLAGS LDFLAGS"
 TOP_EOF
   validate_ops="$validate_ops \$C_OPTIONS"
   config_help_ops="$config_help_ops -cc"
 elif test x$op_cstemx = x1; then
   cat <<"TOP_EOF" >>$out_file
-CXX_OPTIONS="-cxx -cxxflags -ldflags"
+CXX_OPTIONS="-cxx -cxxflags -ldflags CXX CXXFLAGS LDFLAGS"
 TOP_EOF
   validate_ops="$validate_ops \$CXX_OPTIONS"
   config_help_ops="$config_help_ops -cxx"
@@ -250,7 +265,7 @@ fi
 
 cat <<TOP_EOF >>$out_file
 CUSTOM_OPTIONS="$op_params"
-FORMAKE_TOOLS="mkbuildroot $formake_scripts"
+FORMAKE_TOOLS="mkbuildroot abspath relpath listed mkrule $formake_scripts"
 TOP_EOF
 
 cat <<"TOP_EOF" >>$out_file
@@ -268,6 +283,7 @@ config_help_ops=`echo -n "$config_help_ops" | sed 's/^ *//'`
 cat <<TOP_EOF >>$out_file
 ################################################################################
 # OPTIONS
+confighelp -h >/dev/null || exit 1
 optool validate "\$@" - -h -help --help $validate_ops \$CUSTOM_OPTIONS || exit 1
 if optool ifor "\$@" - -h -help --help; then
   confighelp $config_help_ops
@@ -285,6 +301,29 @@ optool rc "\$@" >build.conf
 . ./build.conf
 
 TOP_EOF
+
+if test x$op_no_install = x; then
+  cat <<"TOP_EOF" >>$out_file
+################################################################################
+# VERIFY OPTIONS
+test -n "$PREFIX"      || PREFIX=/usr/local
+test -n "$EXEC_PREFIX" || EXEC_PREFIX=$PREFIX
+test -n "$BINDIR"      || BINDIR=$EXEC_PREFIX/bin
+test -n "$SBINDIR"     || SBINDIR=$EXEC_PREFIX/sbin
+test -n "$LIBEXECDIR"  || LIBEXECDIR=$EXEC_PREFIX/libexec
+test -n "$VARDIR"      || VARDIR=/var
+test -n "$ETCDIR"      || ETCDIR=$PREFIX/etc
+test -n "$LIBDIR"      || LIBDIR=$EXEC_PREFIX/lib
+test -n "$INCDIR"      || INCDIR=$PREFIX/include
+test -n "$SHAREDIR"    || SHAREDIR=$PREFIX/share
+test -n "$MANDIR"      || MANDIR=$SHAREDIR/man
+test -n "$DOCDIR"      || DOCDIR=$SHAREDIR/doc
+
+PACKAGE_SHAREDIR=$SHAREDIR/$PACKAGE_NAME
+PACKAGE_DOCDIR=$SHAREDIR/doc/$PACKAGE_NAME
+
+TOP_EOF
+fi
 
 cat <<TOP_EOF >>$out_file
 ################################################################################
@@ -305,7 +344,7 @@ cat <<"TOP_EOF" >>$out_file
 ################################################################################
 # INIT BUILDROOT
 mkbuildroot $SRCROOT $BUILDROOT || exit 1
-rm -f build.h configure.log
+rm -f configure.log
 
 TOP_EOF
 
@@ -343,38 +382,45 @@ TOP_EOF
   echo "" >>$out_file
 fi
 
-if test -n "$op_sh"; then
-  cat <<TOP_EOF >>$out_file
-################################################################################
-# CUSTOM SCRIPT
-$op_sh
-
-TOP_EOF
-fi
-
 cat <<TOP_EOF >>$out_file
 ################################################################################
-# CONFIG FILES
-optool rc -package-name "\$PACKAGE_NAME" -package-ver \$PACKAGE_VERSION >>build.conf
+# CUSTOM CODE
+# put your custom code here
 TOP_EOF
-if test x"$op_build_h" = x1; then
-  echo "optool def \"\$@\" -package-name \"\$PACKAGE_NAME\" -package-ver \$PACKAGE_VERSION >>build.h" >>$out_file
+if test -n "$op_sh"; then
+  echo "$op_sh" >>$out_file
 fi
+echo "" >>$out_file
 
 cat <<"TOP_EOF" >>$out_file
+################################################################################
+# CONFIG FILES
+optool rc -package-name $PACKAGE_NAME -package-ver $PACKAGE_VERSION \
+          -prefix $PREFIX -exec-prefix $EXEC_PREFIX -bindir $BINDIR -sbindir $SBINDIR \
+          -libexecdir $LIBEXECDIR -vardir $VARDIR -etcdir $ETCDIR -libdir $LIBDIR \
+          -incdir $INCDIR -sharedir $SHAREDIR -mandir $MANDIR -docdir $DOCDIR \
+          -package-sharedir $PACKAGE_SHAREDIR -package-docdir $PACKAGE_DOCDIR >build.conf
+TOP_EOF
+if test x"$op_build_h" = x1; then
+  echo "optool def \"\$@\" -package-name \"\$PACKAGE_NAME\" -package-ver \$PACKAGE_VERSION >build.h" >>$out_file
+fi
+
+if test x$op_no_install = x; then
+  cat <<"TOP_EOF" >>$out_file
 
 ################################################################################
 # MKRULE
 mkrule config -prefix=$PREFIX -exec-prefix=$EXEC_PREFIX -bindir=$BINDIR -sbindir=$SBINDIR \
           -libexecdir=$LIBEXECDIR -libdir=$LIBDIR -incdir=$INCDIR -etcdir=$ETCDIR \
-          -sharedir=$SHAREDIR -mandir=$MANDIR -docdir=$DOCDIR
+          -sharedir=$PACKAGE_SHAREDIR -mandir=$MANDIR -docdir=$PACKAGE_DOCDIR
 TOP_EOF
+fi
 
 cat <<"TOP_EOF" >>$out_file
 
 ################################################################################
 # MKMF
-BUILDROOT=$BUILDROOT $SRCROOT/mkmf
+BUILDROOT=$BUILDROOT $SRCROOT/mkmf || exit 1
 
 ################################################################################
 # FINISH
@@ -386,7 +432,6 @@ chmod +x $out_file
 
 cat <<TOP_EOF
 created script "$out_file"
-formake scripts used: $formake_scripts
 package name: $op_pkgname
 package version: $op_pkgver
 TOP_EOF
diff --git a/src/mkmkmf/test/formake/listed b/src/mkmkmf/test/formake/listed
--- a/src/mkmkmf/test/formake/listed
+++ b/src/mkmkmf/test/formake/listed
@@ -3,460 +3,235 @@
 # Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
 #
 
-VERSION=1.2
+version=1.0
 script_name=`basename $0`
+nl='
+'
+op_ifs=
+list=
 
 print_help() {
-  printf "list [-h|-help] [-version] [-grep <args ...> [-]] [-sed <args ...> [-]] [-rm-headers] [-rm-cfiles]\n"
-  printf "     [-rm-cxxfiles] [-rm-objects] [-grep-headers] [-grep-cfiles]\n"
-  printf "     [-grep-cxxfiles] [-grep-objects] [-pref=<prefix>] [-rm-suffix]\n"
-  printf "     [-suffix-ed <suffix>] [-add-suffix <suffix>] [-ext=<extension> [-ifs <ifs>]\n"
-  printf "     [-merge-lines] [-list] <list>\n"
+  cat <<EOF
+$script_name OPTIONS list..
+$script_name -v
+
+Fileter/edit options may be specified multiple times and are applied in the same
+order.
+
+Filter/edit options:
+  -grep=ARGS          pass list thourgh a grep tool
+  -sed=ARGS           pass list through a sed tool
+  -pref=PREFIX        add prefix to each list item
+  -rm-ext             for every item remove suffix that goes after last dot
+  -suff=SUFIX         add suffix to each list item
+  -edit-ext=EXT       for every item change suffix that goes after last dot
+  -cmd=CMD            pass every item through the specified pipe command
+
+Global options:
+  -ifs=IFS            specify list items delimiter [space]
+EOF
 }
 
 if test $# -eq 0; then
-  print_help
+  echo "$script_name: error. No options specified" >&2
   exit 1
 fi
 
-
-param_sed=false
-param_grep=false
-param_rm_headers=false
-param_rm_cfiles=false
-param_rm_cxxfiles=false
-param_rm_objects=false
-param_grep_headers=false
-param_grep_cfiles=false
-param_grep_cxxfiles=false
-param_grep_objects=false
-param_add_prefix=false
-param_add_suffix=false
-param_suffix_ed=false
-param_rm_suffix=false
-param_ifs=false
-param_merge_lines=false
-
-noption=1
-current_opt=""
-list=
+idx=0
 while test $# -gt 0; do
-  opt_arg=false
-  if test x"$current_opt" = "xlist"; then
-    list="$list$1 "
-  else
-    case $1 in
-    -help|-h)
-      print_help
-      exit 0
-      ;;
-    -version)
-      printf "${VERSION}\n"
-      exit 0
-      ;;
-    -sed)
-      current_opt="sed"
-      sed_args=
-      ;;
-    -grep)
-      current_opt="grep"
-      grep_args=
-      ;;
-    -rm-headers)
-      param_rm_headers=true
-      ;;
-    -rm-cfiles)
-      param_rm_cfiles=true
-      ;;
-    -rm-cxxfiles)
-      param_rm_cxxfiles=true
-      ;;
-    -rm-objects)
-      param_rm_objects=true
-      ;;
-    -grep-headers)
-      param_grep_headers=true
-      ;;
-    -grep-cfiles)
-      param_grep_cfiles=true
-      ;;
-    -grep-cxxfiles)
-      param_grep_cxxfiles=true
-      ;;
-    -grep-objects)
-      param_grep_objects=true
-      ;;
-    -pref=*)
-      prefix=`echo -n "$1" | sed 's/^[^=]*=//'`
-      param_add_prefix=true
-      current_opt=
-      ;;
-    -rm-suffix)
-      param_rm_suffix=true
-      ;;
-    -ext=*)
-      suffix_ed=`echo -n "$1" | sed 's/^[^=]*=//'`
-      param_suffix_ed=true
-      current_opt=
-      ;;
-    -suffix-ed)
-      current_opt="suffix-ed"
-      ;;
-    -add-suffix)
-      current_opt="add-suffix"
-      ;;
-    -ifs)
-      current_opt="ifs"
-      ;;
-    -merge-lines)
-      param_merge_lines=true
-      ;;
-    -list)
-      current_opt="list"
-      ;;
-    -)
-      current_opt=
-      ;;
-    *)
-      opt_arg=true
-      case $current_opt in
-      sed)
-        param_sed=true
-        if test x"$sed_args" = "x"; then
-          sed_args=\'$1\'
-        else
-          sed_args="$sed_args '$1'"
-        fi
-        ;;
-      grep)
-        param_grep=true
-        if test x"$grep_args" = "x"; then
-          grep_args=\'$1\'
-        else
-          grep_args="$grep_args '$1'"
-        fi
-        ;;
-      suffix-ed)
-        param_suffix_ed=true
-        suffix_ed=$1
-        current_opt=
-        ;;
-      add-suffix)
-        param_add_suffix=true
-        add_suffix=$1
-        current_opt=
-        ;;
-      ifs)
-        param_ifs=true
-        ifs=$1
-        current_opt=
-        ;;
-      *)
-        list="$list$1 "
-        ;;
-      esac
-      ;;
-    esac
-  fi
+  case $1 in
+  -h|-help|--help)
+    print_help
+    exit 0
+    ;;
+  -v)
+    printf "$script_name ${version}\n"
+    exit 0
+    ;;
+  -sed=*)
+    op_val=`echo -n "$1" | sed 's/^[^=]*=//'`
+    eval op${idx}_type=sed
+    eval op${idx}_val=\$op_val
+    ;;
+  -grep=*)
+    op_val=`echo -n "$1" | sed 's/^[^=]*=//'`
+    eval op${idx}_type=grep
+    eval op${idx}_val=\$op_val
+    ;;
+  -pref=*)
+    op_val=`echo -n "$1" | sed 's/^[^=]*=//'`
+    eval op${idx}_type=prefix
+    eval op${idx}_val=\$op_val
+    ;;
+  -rm-ext)
+    eval op${idx}_type="rm-ext"
+    ;;
+  -edit-ext=*)
+    op_val=`echo -n "$1" | sed 's/^[^=]*=//'`
+    eval op${idx}_type="edit-ext"
+    eval op${idx}_val=\$op_val
+    ;;
+  -suff=*)
+    op_val=`echo -n "$1" | sed 's/^[^=]*=//'`
+    eval op${idx}_type=suffix
+    eval op${idx}_val=\$op_val
+    ;;
+  -cmd=*)
+    op_val=`echo -n "$1" | sed 's/^[^=]*=//'`
+    eval op${idx}_type=cmd
+    eval op${idx}_val=\$op_val
+    ;;
+  -ifs=*)
+    op_ifs=`echo -n "$1" | sed 's/^[^=]*=//'`
+    ;;
+  *)
+    list="$list $1"
+    ;;
+  esac
   shift
-  if $opt_arg; then
-    false
-  else
-    noption=`expr $noption \+ 1`
-  fi
+  idx=`expr $idx + 1`
 done
 
-  nl='
-'
+opnum=$idx
 
-if test x"$list" = "x"; then
+list=`echo -n "$list" | sed 's/^ *//'`
+
+if test -z "$list"; then
   IFS_save=$IFS
   IFS=$nl
   while read input; do
-    if test x"$list" = "x"; then
+    if test -z "$list"; then
       list=$input
     else
       list="${list}${nl}$input"
     fi
   done
-  if $param_ifs; then
-    false
-  else
-    ifs=$nl
-    param_ifs=true
+  if test -z "$op_ifs"; then
+    op_ifs=$nl
   fi
   IFS=$IFS_save
-else
-  if $param_ifs; then
-    false
-  else
-    ifs=' '
-    param_ifs=true
-  fi
+elif test -z "$op_ifs"; then
+    op_ifs=' '
 fi
 
-if $param_ifs && test x"$ifs" = "x\n"; then
-  ifs=$nl
+if test x"$op_ifs" = "x\n"; then
+  op_ifs=$nl
 fi
 
 IFS_save=$IFS
 IFS=$nl
 
-new_data=""
 data=$list
 for list in $data; do
-  if $param_ifs; then
-    IFS=$ifs
-  else
-    IFS=$IFS_save
-  fi
-  
-  if $param_grep; then
-    new_list=""
-    for item in $list; do
-      if test x"$item" != "x"; then
-        item=`echo $item | eval grep $grep_args`
-        if test x"$item" != "x"; then
-          if test x"$new_list" = "x"; then
-            new_list="$item"
+  IFS=$op_ifs
+
+  idx=0
+  while test $idx -lt $opnum; do
+    eval op_type=\$op${idx}_type
+    eval op_val=\$op${idx}_val
+
+    case $op_type in
+      sed)
+        new_list=
+        for item in $list; do
+          item=`echo -n "$item" | eval sed $op_val`
+          if test -n "$item"; then
+            if test -z "$new_list"; then
+              new_list=$item
+            else
+              new_list="${new_list}${IFS}${item}"
+            fi
+          fi
+        done
+        list=$new_list
+        ;;
+      grep)
+        new_list=
+        for item in $list; do
+          item=`echo -n "$item" | eval grep $op_val`
+          if test -n "$item"; then
+            if test -z "$new_list"; then
+              new_list="$item"
+            else
+              new_list="${new_list}${IFS}${item}"
+            fi
+          fi
+        done
+        list=$new_list
+        ;;
+      prefix)
+        new_list=
+        for item in $list; do
+          item="${op_val}${item}"
+          if test -z "$new_list"; then
+            new_list=$item
           else
             new_list="${new_list}${IFS}${item}"
           fi
-        fi
-      fi
-    done
-    list=$new_list
-  fi
+        done
+        list=$new_list
+        ;;
+      rm-ext)
+        new_list=
+        for item in $list; do
+          item=`echo -n "$item" | sed 's/\.[^.]*$//'`
+          if test -n "$item"; then
+            if test -z "$new_list"; then
+              new_list=$item
+            else
+              new_list="${new_list}${IFS}${item}"
+            fi
+          fi
+        done
+        list=$new_list
+        ;;
+      edit-ext)
+        new_list=
+        for item in $list; do
+          item=`echo -n "$item" | sed 's/\.[^.]*$//'`
+          item="${item}.${op_val}"
+          if test -z "$new_list"; then
+            new_list=$item
+          else
+            new_list="${new_list}${IFS}${item}"
+          fi
+        done
+        list=$new_list
+        ;;
+      suffix)
+        new_list=
+        for item in $list; do
+          item="${item}${op_val}"
+          if test -z "$new_list"; then
+            new_list=$item
+          else
+            new_list="${new_list}${IFS}${item}"
+          fi
+        done
+        list=$new_list
+        ;;
+      cmd)
+        new_list=
+        for item in $list; do
+          item=`echo -n "$item" | eval $op_val`
+          if test -n "$item"; then
+            if test -z "$new_list"; then
+              new_list=$item
+            else
+              new_list="${new_list}${IFS}${item}"
+            fi
+          fi
+        done
+        list=$new_list
+        ;;
+    esac
+    idx=`expr $idx + 1`
+  done
   
-  if $param_rm_headers; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | grep -v '\.h$'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-
-  if $param_rm_cfiles; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | grep -v '\.c$'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-
-  if $param_rm_cxxfiles; then
-    new_list=""
-    for item in $list; do
-      if expr "$item" : '.*\.cxx$' > /dev/null || \
-         expr "$item" : '.*\.cpp$' > /dev/null || \
-         expr "$item" : '.*\.CPP$' > /dev/null || \
-         expr "$item" : '.*\.c++$' > /dev/null || \
-         expr "$item" : '.*\.C++$' > /dev/null || \
-         expr "$item" : '.*\.C$' > /dev/null; then
-        _nop=1
-      else
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-
-  if $param_rm_objects; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | grep -v '\.o$'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-
-  if $param_grep_cfiles; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | grep '\.c$'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if $param_grep_headers; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | grep '\.h$'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if $param_grep_cxxfiles; then
-    new_list=""
-    for item in $list; do
-      if expr "$item" : '.*\.cxx$' > /dev/null || \
-         expr "$item" : '.*\.cpp$' > /dev/null || \
-         expr "$item" : '.*\.CPP$' > /dev/null || \
-         expr "$item" : '.*\.c++$' > /dev/null || \
-         expr "$item" : '.*\.C++$' > /dev/null || \
-         expr "$item" : '.*\.C$' > /dev/null; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-
-  if $param_grep_objects; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | grep '\.o$'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if $param_sed; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | eval sed $sed_args`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-
-  if $param_add_prefix; then
-    new_list=""
-    for item in $list; do
-      item="${prefix}${item}"
-      if test x"$new_list" = "x"; then
-        new_list=$item
-      else
-        new_list="${new_list}${IFS}${item}"
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if $param_rm_suffix; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | sed 's/\.[^.]*$//'`
-      if test x"$item" != "x"; then
-        if test x"$new_list" = "x"; then
-          new_list=$item
-        else
-          new_list="${new_list}${IFS}${item}"
-        fi
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if $param_suffix_ed; then
-    new_list=""
-    for item in $list; do
-      item=`echo $item | sed 's/\.[^.]*$//'`
-      item="${item}.${suffix_ed}"
-      if test x"$new_list" = "x"; then
-        new_list=$item
-      else
-        new_list="${new_list}${IFS}${item}"
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if $param_add_suffix; then
-    new_list=""
-    for item in $list; do
-      item="${item}${add_suffix}"
-      if test x"$new_list" = "x"; then
-        new_list=$item
-      else
-        new_list="${new_list}${IFS}${item}"
-      fi
-    done
-    list=$new_list
-  fi
-  
-  if test x"$list" != "x"; then
-    new_data="${new_data}$list${nl}"
-  fi
+  printf "%s\n" "${list}"
 
   IFS=$nl
 done
-
-IFS=$nl
-iter_one=true
-for line in $new_data; do
-  if $param_merge_lines; then
-    if $iter_one; then
-      printf "%s" "${line}"
-      iter_one=false
-    else
-      if $param_ifs && ! test x"$ifs" = "x$nl"; then
-        printf "%s" "${ifs}$line"
-      else
-        printf "%s" " $line"
-      fi
-    fi
-  else
-    printf "%s\n" "${line}"
-  fi
-done
-
-if $param_merge_lines; then
-  printf "\n"
-fi
 
 IFS=$IFS_save
  
diff --git a/src/mkmkmf/test/formake/mkrule b/src/mkmkmf/test/formake/mkrule
--- a/src/mkmkmf/test/formake/mkrule
+++ b/src/mkmkmf/test/formake/mkrule
@@ -19,9 +19,10 @@ cd "$orig_dir"
 
 print_help() {
   cat <<EOF
-$script_name obj|app|lib|subdir|clean|distclean|install|all OPTIONS
+$script_name init|obj|app|lib|subdir|clean|distclean|install OPTIONS
 $script_name config OPTIONS
 $script_name -v
+  init        generate standard init macros and rules
   obj         generate rules that compile objects from sources
   app         generate rule that link application from objects
   lib         generate rule that create library from objects
@@ -29,11 +30,16 @@ $script_name -v
   clean       generate rule that cleans files
   distclean   generate rule that cleans build configuration files
   install     generate rule that installs files on system
-  all         generate simple 'all:' rule
   config      configure $script_name
   -v          print version
 
 First parameter specifies the mode. To get help on each mode run '$script_name MODE -help'
+EOF
+}
+
+print_init_help() {
+  cat <<EOF
+$script_name init
 EOF
 }
 
@@ -46,6 +52,9 @@ $script_name obj [OPTIONS] -src SRC..
   -pic             enable PIC flags
   -d DIR           output directory for generated objects
   -p PREREQ..      additional prerequisites of rules
+  -disable-mkdep   disable generating source dependencies for Makefile
+  -mkdep CMD       specify path to mkdep tool
+  -builddir=PATH   path to a build directory where makefile is placed
   -rc FILE         create RC file
   -var[=PREFIX]    create a Make variable [PREFIX_]OBJECTS containing a list of generated objects
   -src SRC..       list of source files
@@ -130,14 +139,9 @@ print_install_help() {
 $script_name install TYPE [OPTIONS] FILE..
   TYPE             files type: bin, sbin, libexec, lib, inc, share, man[1-8], doc, etc
   -t TARGET        specify phony target that start generated rules
-  -path PATH       installation path
+  -rename NAME     set destination file name
+  -d DIR           installation directory
   FILE..           files to install. RC files are accepted
-EOF
-}
-
-print_all_help() {
-  cat <<EOF
-$script_name all
 EOF
 }
 
@@ -165,6 +169,10 @@ print_version() {
 
 abs_path() {
   _sub_orig_dir=`pwd`
+  if test $# = 0; then
+    abs_path_ret=
+    return
+  fi
   if test $# = 2; then
     _arg_orig_dir=$1
     _arg=$2
@@ -197,8 +205,38 @@ abs_path() {
     else
       abs_path_ret="$_sub_orig_dir/$_arg"
     fi
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#//*#/#g'`
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/*$#/#'`
+    string_prev=
+    while test "x$abs_path_ret" != "x$string_prev" ; do
+      string_prev=$abs_path_ret
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/[^/][^/][^/][^/]*/\.\./#/#g' | sed 's#/[^/][^/.]/\.\./#/#g' | sed 's#/[^/.][^/]/\.\./#/#g' | sed 's#/[^/.]/\.\./#/#g'`
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#^/\.\./#/#' | sed 's#^/\.\.$#/#'`
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/\./#/#g' | sed 's#/\.$#/#'`
+    done
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/$##' | sed 's#^$#/#'`
   fi
 }
+
+rel_path() {
+  abs_path "$1"
+  file_from=$abs_path_ret
+  if test -n "$2"; then
+    abs_path "$2"
+    file_to=$abs_path_ret
+  else
+    file_to=`pwd`
+  fi
+
+  file_from_tmp=$file_from
+  while test `expr "$file_to" : "^$file_from_tmp"` -eq 0; do
+    file_from_tmp=`dirname "$file_from_tmp"`
+  done
+  dir_up=`echo -n "$file_from" | sed "s:^$file_from_tmp::" | sed 's:^/::' | sed 's:[^/][^/]*:..:g'`
+  dir_down=`echo -n "$file_to" | sed "s:^$file_from_tmp::" | sed 's:^/::'`
+  rel_path_ret=`echo -n "$dir_up/$dir_down" | sed 's:^/*$:.:' | sed 's:^/*::' | sed 's:/*$::'`
+}
+
 
 get_pofig() {
   pofig -h >/dev/null 2>&1
@@ -236,15 +274,34 @@ get_cstem() {
   fi
 }
 
+get_mkdep() {
+  if test -n "$op_mkdep_cmd"; then
+    MKDEP=$op_mkdep_cmd
+  else
+    $script_dir/mkdep -h >/dev/null 2>&1
+    if test $? -eq 0; then
+      if test -n "$op_builddir"; then
+        rel_path $op_builddir $script_dir/mkdep
+      else
+        rel_path ./ $script_dir/mkdep
+      fi
+      MKDEP=$rel_path_ret
+    else
+      mkdep -h >/dev/null 2>&1
+      if test $? -eq 0; then
+        MKDEP=mkdep
+      else
+        echo "$script_name: error: mkdep not found" >&2
+        exit 1
+      fi
+    fi
+  fi
+}
+
 get_random() {
 # RANDOM METHOD 1
   if test -z "$RANDOM"; then
     if test -f /dev/urandom; then
-      dev_random=/dev/urandom
-    elif test -f /dev/random; then
-      dev_random=/dev/random
-    fi
-    if test -n "$dev_random"; then
       fold --help >/dev/null 2>&1
       if test $? != 127; then
         have_fold=1
@@ -254,7 +311,7 @@ get_random() {
         have_head=1
       fi
       if test x$have_fold$have_head = x11; then
-        RANDOM=`cat $dev_random | tr -dc 'a-fA-F0-9' | fold -w 8 | head -n 1`
+        RANDOM=`cat /dev/urandom | tr -dc 'a-fA-F0-9' | fold -w 8 | head -n 1`
       fi
     fi
   fi
@@ -263,7 +320,7 @@ get_random() {
   if test -z "$RANDOM"; then
     shuf --help >/dev/null 2>&1
     if test $? != 127; then
-      RANDOM=`shuf -i 0-9999 -n 1`
+      RANDOM=`shuf -i 0-999999 -n 1`
     fi
   fi
 
@@ -271,7 +328,7 @@ get_random() {
   if test -z "$RANDOM"; then
       mktemp --help >/dev/null 2>&1
       if test $? != 127; then
-        RANDOM=`mktemp -u "XXXX"`
+        RANDOM=`mktemp -u "XXXXXX"`
       fi
   fi
 }
@@ -320,6 +377,9 @@ mkobj() {
 
   get_pofig
   get_cstem
+  if test x$op_disable_mkdep = x; then
+    get_mkdep
+  fi
   
   cc_cmd=`$CSTEM -cmd -cflags`
   if test -z "$cc_cmd"; then
@@ -344,6 +404,7 @@ mkobj() {
   case "$os_type" in
     gnulinux|*)
       obj_ext="o"
+      modern_make=1
       ;;
   esac
   
@@ -375,13 +436,43 @@ EOF
     else
       echo "$src_base" >> $tmp_file_base
       echo "$src" >> $tmp_file_full
-      object=`echo -n "$src_base" | sed "s/\.[^.]*$/.$obj_ext/"`
-      object="$op_dir$object"
+      name_base=`echo -n "$src_base" | sed 's/\.[^.]*$//'`
+      object="$op_dir${name_base}.$obj_ext"
       object_list="$object_list $object"
-      cat <<EOF
-$object: $src $op_prereq
-	$cc_cmd -c $src -o $object
+      if test x$op_disable_mkdep = x; then
+        dep_file=".deps/$op_dir${name_base}.d"
+        cat <<EOF
+$object: $src $op_prereq $dep_file
+	@test -d .deps/$op_dir || mkdir -p .deps/$op_dir
+	@$MKDEP -o $object -stdout $src >$dep_file
 EOF
+        if test -n "$op_dir"; then
+          echo "	@test -d $op_dir || mkdir -p $op_dir"
+        fi
+        echo "	$cc_cmd -c $src -o $object"
+        if test x$modern_make = x1; then
+          cat <<EOF
+-include $dep_file
+$dep_file:
+EOF
+        else
+	      mkdir -p .deps/$op_dir
+	      echo "" >$dep_file
+          cat <<EOF
+$dep_file:
+	@mkdir -p .deps/$op_dir
+	@echo "" >$dep_file
+include $dep_file
+EOF
+        fi
+      else # disable mkdep
+        echo "$object: $src $op_prereq"
+        if test -n "$op_dir"; then
+          echo "	@test -d $op_dir || mkdir -p $op_dir"
+        fi
+        echo "	$cc_cmd -c $src -o $object"
+      fi
+      echo ""
     fi
   done
   rm -f $tmp_file_base
@@ -398,7 +489,7 @@ EOF
   else
     get_random
     if test -n "$RANDOM"; then
-      clean_target="clean-obj$RANDOM"
+      clean_target="clean-obj-$RANDOM"
     fi
   fi
 
@@ -407,7 +498,29 @@ EOF
 clean: $clean_target
 $clean_target:
 	rm -f $object_list
+
 EOF
+  fi
+  
+  if test x$op_disable_mkdep = x; then
+    distclean_target=
+    if test -n "$op_target"; then
+      distclean_target="distclean-$op_target"
+    else
+      get_random
+      if test -n "$RANDOM"; then
+        distclean_target="distclean-obj-$RANDOM"
+      fi
+    fi
+
+    if test -n "$distclean_target"; then
+      cat <<EOF
+distclean: $distclean_target
+$distclean_target: $clean_target
+	rm -Rf .deps
+
+EOF
+    fi
   fi
   
   if test -n "$op_rc"; then
@@ -419,7 +532,6 @@ EOF
       echo "LANG=\"c++\"" >> $op_rc
     fi
   fi
-  echo ""
 }
 
 
@@ -438,12 +550,6 @@ mkapp() {
     exit 1
   fi
 
-  cat <<EOF
-################################################################################
-# APPLICATIONS
-# $script_name $script_options
-EOF
-  
   os_type=`$POFIG -os`
   case "$os_type" in
     gnulinux|*)
@@ -461,6 +567,12 @@ EOF
   
   app_local="$op_dir$op_name$exe_ext"
 
+  cat <<EOF
+################################################################################
+# APPLICATIONS
+# $script_name $script_options
+EOF
+  
   if test x$op_var = x1; then
     echo "${op_var_prefix}PROGRAM = $app_local"
   fi
@@ -482,10 +594,11 @@ EOF
     if test -z "$op_install_path"; then
       op_install_path=$BINDIR
     fi
+    file_base=`basename $app_local`
     cat <<EOF
 install: install-$op_name
 install-$op_name: $app_local
-	$INSTALL -m 0755 $app_local $op_install_path
+	$INSTALL -m 0755 -D $app_local $op_install_path/$file_base
 EOF
   fi
 
@@ -493,6 +606,7 @@ EOF
 clean: clean-$op_name
 clean-$op_name:
 	rm -f $app_local
+distclean: clean-$op_name
 EOF
   
   if test -n "$op_rc"; then
@@ -534,12 +648,6 @@ mklib() {
     fi
   fi
   
-  cat <<EOF
-################################################################################
-# LIBRARIES
-# $script_name $script_options
-EOF
-
   if test x$op_shared = x1; then
     lib_type=shared
   else
@@ -614,6 +722,12 @@ $cmd"
   done
   IFS=$IFS_save
   
+  cat <<EOF
+################################################################################
+# LIBRARIES
+# $script_name $script_options
+EOF
+
   if test x$op_var = x1; then
     echo "${op_var_prefix}LIB_FILES = $lib_targets"
     echo "${op_var_prefix}LIB_NAME = $op_name"
@@ -653,10 +767,11 @@ install: install-$op_name
 install-$op_name: $lib_targets
 EOF
     for file in $lib_regular; do
+      file_base=`basename $file`
       if test x$op_shared = x1; then
-	    echo "	$INSTALL -m 0755 $file $op_install_path"
+	    echo "	$INSTALL -m 0755 -D $file $op_install_path/$file_base"
       else
-	    echo "	$INSTALL -m 0644 $file $op_install_path"
+	    echo "	$INSTALL -m 0644 -D $file $op_install_path/$file_base"
       fi
     done
     for file in $lib_symbolic; do
@@ -668,6 +783,7 @@ EOF
 clean: clean-$op_name
 clean-$op_name:
 	rm -f $lib_targets
+distclean: clean-$op_name
 EOF
   
   if test -n "$op_rc"; then
@@ -696,17 +812,21 @@ mksubdir() {
 # $script_name $script_options
 EOF
   if test x$op_all = x1; then
-    echo "all: $op_dirs"
+    echo "all: subdirs"
+    print_nl=1
   fi
 
   if test -n "$op_target"; then
     echo "$op_target: $op_dirs"
   fi
 
-  echo ""
+  test x$print_nl = x1 && echo ""
+  print_nl=
+
   for dir in $op_dirs; do
     cat <<EOF
-$dir: $op_prereq
+subdirs: subdir-$dir
+subdir-$dir: $op_prereq
 	\$(MAKE) -C $dir
 EOF
     if test x$op_install = x1; then
@@ -741,22 +861,22 @@ mkclean() {
     exit 1
   fi
 
+  if test -z "$op_target"; then
+    get_random
+    op_target="clean-$RANDOM"
+  fi
+
   cat <<EOF
 ################################################################################
 # CLEAN
 # $script_name $script_options
 EOF
 
-  if test -z "$op_target"; then
-    get_random
-    op_target="clean$RANDOM"
-  fi
-
   cat <<EOF
-
 clean: $op_target
 $op_target:
 	rm -Rf $op_files
+distclean: $op_target
 EOF
   echo ""
 }
@@ -767,19 +887,18 @@ mkdistclean() {
     exit 1
   fi
 
+  if test -z "$op_target"; then
+    get_random
+    op_target="distclean-$RANDOM"
+  fi
+
   cat <<EOF
 ################################################################################
 # DISTCLEAN
 # $script_name $script_options
 EOF
 
-  if test -z "$op_target"; then
-    get_random
-    op_target="distclean$RANDOM"
-  fi
-
   cat <<EOF
-
 distclean: $op_target
 $op_target:
 	rm -Rf $op_files
@@ -793,23 +912,16 @@ mkinstall() {
     exit 1
   fi
 
-  cat <<EOF
-################################################################################
-# INSTALLATION FILES
-# $script_name $script_options
-EOF
+  num_files=`echo "$op_files" | wc -w`
+  if test -n "$op_rename" && test $num_files -gt 1; then
+    echo "$script_name: option '-rename' can't be used for multiple installation files" >&2
+    exit 1
+  fi
+
   if test -z "$op_target"; then
     get_random
     op_target="install-$op_type-$RANDOM"
   fi
-  case $op_type in
-    man*)
-      target_base="install-man"
-      ;;
-    *)
-      target_base="install-$op_type"
-      ;;
-  esac
 
   case $op_type in
     bin)
@@ -851,16 +963,26 @@ EOF
       ;;
   esac
 
-  test -z "$op_install_path" || dir=$op_install_path
+  test -z "$op_dir" || dir=$op_dir
+
+  cat <<EOF
+################################################################################
+# INSTALLATION FILES
+# $script_name $script_options
+EOF
 
   cat <<EOF
 install: $op_target
-$target_base: $op_target
 $op_target: $op_files
 EOF
-  for file in $op_files; do
-    printf "\t%s\n" "install -m $perm $file $dir"
-  done
+  if test -n "$op_rename"; then
+    printf "\t%s\n" "$INSTALL -m $perm -D $op_files $dir/$op_rename"
+  else
+    for file in $op_files; do
+      file_base=`basename $file`
+      printf "\t%s\n" "$INSTALL -m $perm -D $file $dir/$file_base"
+    done
+  fi
   echo ""
 }
 
@@ -877,6 +999,9 @@ case $1 in
   -v)
     print_version
     exit 0
+    ;;
+  init)
+    op_mode=init
     ;;
   config)
     op_mode=config
@@ -901,9 +1026,6 @@ case $1 in
     ;;
   install)
     op_mode=install
-    ;;
-  all)
-    op_mode=all
     ;;
   *)
     echo "$script_name: error: invalid parameter $1" >&2
@@ -942,6 +1064,9 @@ while test $# -gt 0; do
         config)
           print_config_help
           ;;
+        init)
+          print_init_help
+          ;;
         obj)
           print_obj_help
           ;;
@@ -963,11 +1088,16 @@ while test $# -gt 0; do
         install)
           print_install_help
           ;;
-        all)
-          print_all_help
-          ;;
       esac
       exit 0
+      ;;
+    -builddir=*)
+      if test $op_mode != obj; then
+        echo "$script_name: error: invalid parameter $1 for current mode" >&2
+        exit 1
+      fi
+      op_builddir=`echo -n "$1" | sed 's/^[^=]*=//'`
+      current_opt=
       ;;
     -t)
       case $op_mode in
@@ -1016,7 +1146,7 @@ while test $# -gt 0; do
       ;;
     -d)
       case $op_mode in
-        obj|app|lib|subdir)
+        obj|app|lib|subdir|install)
           : ;;
         *)
           echo "$script_name: error: invalid parameter $1 for current mode" >&2
@@ -1052,6 +1182,27 @@ while test $# -gt 0; do
       fi
       op_prereq=$1
       current_opt=prereq
+      ;;
+    -disable-mkdep)
+      if test $op_mode != obj; then
+        echo "$script_name: error: invalid parameter $1 for current mode" >&2
+        exit 1
+      fi
+      op_disable_mkdep=1
+      current_opt=
+      ;;
+    -mkdep)
+      if test $op_mode != obj; then
+        echo "$script_name: error: invalid parameter $1 for current mode" >&2
+        exit 1
+      fi
+      shift
+      if test -z "$1"; then
+        echo "$script_name: error: parameter -mkdep requires argument" >&2
+        exit 1
+      fi
+      op_mkdep_cmd=$1
+      current_opt=
       ;;
     -rc)
       case $op_mode in
@@ -1256,17 +1407,17 @@ while test $# -gt 0; do
       op_distclean=1
       current_opt=
       ;;
-    -path)
+    -rename)
       if test $op_mode != install; then
         echo "$script_name: error: invalid parameter $1 for current mode" >&2
         exit 1
       fi
       shift
       if test -z "$1"; then
-        echo "$script_name: error: parameter -path requires argument" >&2
+        echo "$script_name: error: parameter -rename requires argument" >&2
         exit 1
       fi
-      op_install_path=$1
+      op_rename=$1
       current_opt=
       ;;
     -prefix=*)
@@ -1475,13 +1626,15 @@ case $op_mode in
   install)
     mkinstall
     ;;
-  all)
+  init)
     cat <<EOF
 ################################################################################
-# ALL
+# INIT
 # $script_name $script_options
 all:
-install: all
+install:
+clean:
+distclean:
 
 EOF
     ;;
