update scripts according to updated optool interface

diff --git a/formake/optool b/formake/optool
--- a/formake/optool
+++ b/formake/optool
@@ -1,6 +1,7 @@
 #!/bin/sh
 #
-# Author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
+# Formake optool
+# author: Oleksiy Chernyavskyy <ochern@rocketmail.com>
 #
 
 script_name=`basename $0`
@@ -24,6 +25,7 @@ if test -n "$OPTOOL" && test -z "$OPTOOL_REDIRECT"; then
 fi
 ################################################################################
 
+op_xh=
 sbs_param=
 disable_special=
 param_skip=
@@ -36,7 +38,7 @@ Command-line options processing tool
 
 $script_name dump [-p PREFIX] [-n] [-] OPTIONS
 $script_name hdump [-p PREFIX] [-n] [-] OPTIONS
-$script_name validate VALID_OPTIONS - OPTIONS
+$script_name validate [xh] VALID_OPTIONS - OPTIONS
 $script_name test [!] [any] COND_OPTIONS - OPTIONS
 $script_name source OPTIONS
 
@@ -53,6 +55,7 @@ dump and hdump options:
   -          end of internal options [optional]
 
 validate options:
+  xh             ignore the number of leading hyphens in options
   VALID_OPTIONS  list of valid options
   -              delimiter between valid options and input options
 
@@ -164,31 +167,39 @@ EOF
     ;;
   xvalidate)
     shift
+    if test x"$1" = xxh; then
+      shift
+      op_xh=1
+    fi
     op_delim=
     while test $# -gt 0; do
+      param=$1
+      if test x$op_xh = x1; then
+        param=`echo -n "$param" | sed 's/^--*/-/'`
+      fi
       if test -z "$op_delim"; then
-        case "$1" in
+        case "$param" in
           -)
             op_delim=1
             ;;
           *)
-            sbs_param=`echo -n "$1" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
+            sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
             eval SBS_VALID_$sbs_param=1
             ;;
         esac
       else
-        case "$1" in
+        case "$param" in
           -*|*=*)
-            sbs_param=`echo -n "$1" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
+            sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
             eval is_valid=\$SBS_VALID_$sbs_param
             if test x$is_valid != x1; then
-              echo "invalid parameter: $1" >&2
+              echo "invalid parameter: $param" >&2
               exit 1
             fi
             ;;
           *)
             if test -z "$sbs_param"; then
-              echo "invalid parameter: $1" >&2
+              echo "invalid parameter: $param" >&2
               exit 1
             fi
             ;;
