created 'formake' master script. Renamed fmkmf -> formake-mkmf, fminstall -> formake-install, fmconfigure -> formake-configure, fmpackage -> formake-package

diff --git a/src/formake-configure/formake-configure b/src/formake-configure/formake-configure
--- a/src/formake-configure/formake-configure
+++ b/src/formake-configure/formake-configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Formake fmconfigure
+# Formake formake-configure
 #
 # Copyright (c) 2015-2017, Oleksiy Chernyavskyy
 # All rights reserved.
@@ -25,9 +25,14 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-version_string="fmconfigure 1.0"
+version_string="formake-configure 1.0"
 
 script_name=`basename "$0"`
+orig_dir=`pwd`
+cd `dirname $0`
+script_dir=`pwd`
+cd $orig_dir
+
 script_options="$@"
 tmp_help=/tmp/mkconf_help_$$.txt
 rm -f $tmp_help
@@ -196,10 +201,10 @@ fi
 formake_scripts=`echo -n "$formake_scripts" | sed 's/^ *//'`
 
 if test x$op_fminstall = x1; then
-  if fminstall -h >/dev/null; then
+  if $script_dir/formake-install -h >/dev/null; then
     :
   else
-    echo "$script_name: fminstall script not found" >&2
+    echo "$script_name: $script_dir/formake-install script not found" >&2
     clean_exit 1
   fi
   test -d $out_file_dir/formake || mkdir -p $out_file_dir/formake
@@ -207,14 +212,14 @@ if test x$op_fminstall = x1; then
     echo "$script_name: could not create Formake directory $out_file_dir/formake" >&2
     clean_exit 1
   fi
-  fminstall -d $out_file_dir/formake -std $formake_scripts || clean_exit 1
+  $script_dir/formake-install -d $out_file_dir/formake -std $formake_scripts || clean_exit 1
 fi
 
 rm_out_file=1
 cat <<TOP_EOF >$out_file
 #!/bin/sh
 ################################################################################
-# Generated by Formake fmconfigure
+# Generated by formake-configure
 TOP_EOF
 date >/dev/null 2>&1
 if test $? -eq 0; then
