improved options parsing

diff --git a/src/mkpackage/_mkpackage b/src/mkpackage/_mkpackage
--- a/src/mkpackage/_mkpackage
+++ b/src/mkpackage/_mkpackage
@@ -141,6 +141,10 @@ while test $# -gt 0; do
       s_relpath=1
       have_list=1
       ;;
+    *)
+      echo "$script_name: invalid option: $1" >&2
+      exit 1
+      ;;
   esac
   shift
 done
