cstem: minor fixes and improvements

diff --git a/scripts/cstem/cstem+ b/scripts/cstem/cstem+
--- a/scripts/cstem/cstem+
+++ b/scripts/cstem/cstem+
@@ -114,11 +114,19 @@ script_dir=`dirname "$script_abs"`
 out_format=
 config_file="$script_dir/cstem+.conf"
 ext="C"
-tmp_dir=/tmp/cstem_$$
+test_dir=/tmp/cstem_$$
+if test -d $test_dir || test -f $test_dir; then
+  rm -rf $test_dir
+fi
+mkdir $test_dir
+if test ! -d $test_dir; then
+  echo "$script_name: error: could not create temporary directory $test_dir" >&2
+  exit 1
+fi
 version_string="0.5"
 cc_is_cross=0
-headers=/tmp/cstem_inc_headers_$$
-rm -f $headers
+headers=$test_dir/cstem_inc_headers
+cstem_log=$test_dir/cstem.log
 
 ################################################################################
 # LOAD CONFIG
@@ -498,9 +506,7 @@ check_cc() {
       ;;
   esac
 
-  test_dir=/tmp/cstem_data_$$
-  rm -rf $test_dir
-  mkdir $test_dir
+  rm -f $test_dir/*
   cd $test_dir
 
   test_h="cc_test.h"
@@ -514,7 +520,6 @@ EOF
   ret_code=$?
   if test $ret_code -ne 0; then
     cd $orig_dir
-    rm -rf $test_dir
     return
   fi
 
@@ -544,14 +549,11 @@ EOF
   fi
 
   cd $orig_dir
-  rm -rf $test_dir
 }
 
 get_hdr_defs() {
   test_src="test.$ext"
-  test_dir=/tmp/cstem_data_$$
-  rm -rf $test_dir
-  mkdir $test_dir
+  rm -f $test_dir/*
   cd $test_dir
 
   for hdr in "<android/api-level.h>" "<sys/neutrino.h>" "<version.h>" "<limits.h>" "<stdint.h>" "<sys/types.h>" "<sys/cdefs.h>" "<features.h>" "<limits.h>" "<unistd.h>"; do
@@ -568,7 +570,6 @@ EOF
   done
 
   cd $orig_dir
-  rm -rf $test_dir
 }
 
 read_cc_props() {
@@ -584,21 +585,17 @@ read_cc_props() {
   prop_posix=
   prop_sus=
 
-  probe_h="/tmp/cstem_$$.$ext"
+  probe_h="$test_dir/cstem_$$.$ext"
   rm -f $probe_h
   if test -f $headers; then
     cat $headers >$probe_h
-    rm -f $headers
   fi
   cat $script_abs | sed -n -e '/\* COMPILER DEFINES \*/,$p' | grep -v "^EOF" >> $probe_h
-  probe_h_out="/tmp/cstem_$$_out"
+  probe_h_out="$test_dir/cstem_$$_out"
   $cc_cmd $CXXFLAGS $CPP_FLAG $probe_h 2>/dev/null > $probe_h_out
-  probe_sh="/tmp/cstem_$$.sh"
+  probe_sh="$test_dir/cstem_$$.sh"
   cat $probe_h_out | grep "^D[SV][EA][TL]" | sed 's/= */=/' | sed 's/ *$//' | sed 's/=\(.*\)$/="\1"/' | sed 's/""*/"/g' | sed 's/ *= */=/' | sed 's/="*$/=/' > $probe_sh
   . $probe_sh
-  rm -f $probe_sh
-  rm -f $probe_h_out
-  rm -f $probe_h
 
   if test -n "$DSET__cplusplus_cli"; then
     prop_std=cxx_cli
@@ -1268,8 +1265,8 @@ read_cc_props() {
   fi
 
   if test -z "$prop_data_model" && test $cc_is_cross = 0; then
-    dm_src=/tmp/cstem_dm_$$.$ext
-    dm_exe=/tmp/cstem_dm_$$
+    dm_src=$test_dir/cstem_dm_$$.$ext
+    dm_exe=$test_dir/cstem_dm_$$
     cat >$dm_src <<"EOF"
 #include <stdio.h>
 
@@ -1395,8 +1392,8 @@ EOF
   fi
 
   if test -z "$prop_endianness" && test $cc_is_cross = 0; then
-    border_src=/tmp/cstem_border_$$.$ext
-    border_exe=/tmp/cstem_border_$$
+    border_src=$test_dir/cstem_border_$$.$ext
+    border_exe=$test_dir/cstem_border_$$
     cat >$border_src <<"EOF"
 #include <stdio.h>
 
@@ -1512,7 +1509,7 @@ perform_probe() {
 
   if test x$cc_is_ok != x1; then
     printf "%s\n" "${script_name}: C++ compiler not found" >&2
-    exit 1
+    clean_exit 1
   fi
 
   if test -n "$CXXFLAGS"; then
@@ -1521,7 +1518,7 @@ perform_probe() {
     check_cc
     if test x$cc_is_ok != x1; then
       printf "%s\n" "${script_name}: invalid C++ flags: $CXXFLAGS" >&2
-      exit 1
+      clean_exit 1
     fi
   fi
   if test -n "$LDFLAGS"; then
@@ -1561,7 +1558,6 @@ clean_exit() {
   if test $exit_status != 0 && test x$op_echo_fail = x1 && test -f $tmp_buf; then
     cat $tmp_buf
   fi
-  rm -f $tmp_buf
 
   if test -f $cstem_log; then
     if test x$op_echo_log = x1; then
@@ -1573,9 +1569,9 @@ clean_exit() {
     fi
   fi
   cd $orig_dir
-  rm -rf $tmp_dir
-  rm -f $cstem_log
-
+  if test -d $test_dir; then
+    rm -rf $test_dir
+  fi
   exit $exit_status
 }
 
@@ -1597,9 +1593,8 @@ log_src() {
 }
 
 setup_test_dir() {
-  rm -f $tmp_dir
-  mkdir $tmp_dir
-  cd $tmp_dir
+  rm -f $test_dir/*
+  cd $test_dir
   
   test_src_base=test_src_base.$ext
   
@@ -1615,11 +1610,11 @@ setup_test_dir() {
 case x"$1" in
   x-h|x-help|x--help)
     print_help
-    exit 0
+    clean_exit 0
     ;;
   x-help-props)
     print_help_props
-    exit 0
+    clean_exit 0
     ;;
   xconfig)
     mode_config=1
@@ -1639,7 +1634,7 @@ case x"$1" in
     ;;
   x-v)
     print_version
-    exit 0
+    clean_exit 0
     ;;
   *)
     mode_probe=1
@@ -1668,7 +1663,7 @@ if test x$mode_config = x1; then
         ;;
       *)
         printf "%s\n" "$script_name: invalid parameter $1" >&2
-        exit 1
+        clean_exit 1
         ;;
     esac
     shift
@@ -1679,7 +1674,7 @@ if test x$mode_config = x1; then
       echo "" > $config_file 2>/dev/null
       if test $? != 0; then
         echo "$script_name: error: could not modify config file $config_file" >&2
-        exit 1
+        clean_exit 1
       fi
     else
       (touch $config_file >/dev/null) 2>/dev/null
@@ -1687,7 +1682,7 @@ if test x$mode_config = x1; then
         :
       else
         echo "$script_name: error: could not create config file $config_file" >&2
-        exit 1
+        clean_exit 1
       fi
     fi
 
@@ -1707,7 +1702,7 @@ if test x$mode_config = x1; then
     (rm -f $config_file >/dev/null) 2>/dev/null
   fi
 
-  exit 0
+  clean_exit 0
 fi
 
 if test -f $config_file; then
@@ -1785,7 +1780,7 @@ if test x$mode_probe = x1; then
         ;;
       *)
         printf "%s\n" "$script_name: invalid parameter $1" >&2
-        exit 1
+        clean_exit 1
         ;;
     esac
     shift
@@ -1843,13 +1838,12 @@ EOF
     fi
   fi
 
-  exit 0
+  clean_exit 0
 fi
 
 if test x$mode_test = x1; then
-  tmp_buf="/tmp/cstem_$$_buf.txt"
+  tmp_buf="$test_dir/cstem_buf.txt"
   rm -f $tmp_buf
-  cstem_log=/tmp/cstem$$.log
 
   current_opt=
   def_num=0
@@ -3011,7 +3005,7 @@ if test x$mode_def = x1; then
   done
 
   if test -z "$op_def"; then
-    exit 0
+    clean_exit 0
   fi
   CXXFLAGS="$op_with_flags $CXXFLAGS $CXXFLAGS_ADD"
   op_with_flags=$CXXFLAGS
@@ -3111,7 +3105,7 @@ fi
 
 
 
-exit 0
+clean_exit 0
 
 
 cat <<EOF
