merged pofig iftool and iflib into syscap. Very much of other changes

diff --git a/src/mkconfigure/test/formake/optool b/src/mkconfigure/test/formake/optool
--- a/src/mkconfigure/test/formake/optool
+++ b/src/mkconfigure/test/formake/optool
@@ -10,8 +10,8 @@ script_dir=`dirname $0`
 # LOAD CONFIG
 PATH=$FORMAKE:$PATH
 OPTOOL=
-if test -f $script_dir/formake.conf; then
-  . $script_dir/formake.conf
+if test -f $script_dir/config.rc; then
+  . $script_dir/config.rc
 fi
 test -n "$FORMAKE_OPTOOL" && OPTOOL=$FORMAKE_OPTOOL
 if test -n "$OPTOOL" && test -z "$OPTOOL_REDIRECT"; then
@@ -32,13 +32,35 @@ no_case_change=
 case x$1 in
   x-h|x-help|x--help)
     cat <<EOF
-Usage: $script_name dump [-p <PREFIX>] [-nc] [-] OPTIONS
-       $script_name hdump [-p <PREFIX>] [-nc] [-] OPTIONS
-       $script_name validate OPTIONS - VALID_OPTIONS
-       $script_name if OPTIONS - COND_OPTIONS
-       $script_name ifor OPTIONS - COND_OPTIONS
-       $script_name ifhelp OPTIONS
-       $script_name source OPTIONS
+Command-line options processing tool
+
+$script_name dump [-p PREFIX] [-n] [-] OPTIONS
+$script_name hdump [-p PREFIX] [-n] [-] OPTIONS
+$script_name validate VALID_OPTIONS - OPTIONS
+$script_name test [!] [any] COND_OPTIONS - OPTIONS
+$script_name source OPTIONS
+
+Modes:
+  dump       convert all options to SHELL variables: VARIABLE="VALUE"
+  hdump      convert all options to CPP defines: #define MACRO "VALUE"
+  validate   check options with a list of valid options
+  test       test if options have all or any of specified conditional options
+  source     generate SHELL script file and print it's path to stdout
+
+dump and hdump options:
+  -p PREFIX  add prefix to every variable name: <PREFIX>VARIABLE="VALUE"
+  -n         do not convert options to upper case
+  -          end of internal options [optional]
+
+validate options:
+  VALID_OPTIONS  list of valid options
+  -              delimiter between valid options and input options
+
+test options:
+  !             reverse result status
+  any           return True if any conditional option is found
+  COND_OPTIONS  list of conditional options to check for
+  -             delimiter between conditional options and input options
 EOF
     exit 0
     ;;
@@ -49,11 +71,18 @@ EOF
       case "$1" in
         -*|*=*)
           if test -n "$sbs_param"; then
-            test -n "$sbs_param_val$sbs_param_set" || sbs_param_val=1
             if test $mode = dump; then
-              echo "$sbs_param=\"$sbs_param_val\""
+              if test -n "$sbs_param_val$sbs_param_set"; then
+                echo "$sbs_param=\"$sbs_param_val\""
+              else
+                echo "FLAG_$sbs_param=1"
+              fi
             else
-              echo "#define $sbs_param \"$sbs_param_val\""
+              if test -n "$sbs_param_val$sbs_param_set"; then
+                echo "#define $sbs_param \"$sbs_param_val\""
+              else
+                echo "#define FLAG_$sbs_param 1"
+              fi
             fi
             sbs_param=
           fi
@@ -73,7 +102,7 @@ EOF
                 fi
                 param_skip=1
                 ;;
-              -nc)
+              -n)
                 no_case_change=1
                 param_skip=1
                 ;;
@@ -117,127 +146,117 @@ EOF
       shift
     done
     if test -n "$sbs_param"; then
-      test -n "$sbs_param_val$sbs_param_set" || sbs_param_val=1
       if test $mode = dump; then
-        echo "$sbs_param=\"$sbs_param_val\""
+        if test -n "$sbs_param_val$sbs_param_set"; then
+          echo "$sbs_param=\"$sbs_param_val\""
+        else
+          echo "FLAG_$sbs_param=1"
+        fi
       else
-        echo "#define $sbs_param \"$sbs_param_val\""
+        if test -n "$sbs_param_val$sbs_param_set"; then
+          echo "#define $sbs_param \"$sbs_param_val\""
+        else
+          echo "#define FLAG_$sbs_param 1"
+        fi
       fi
     fi
     exit 0
     ;;
   xvalidate)
     shift
-    test $# -ne 0 || exit 0
-    n=$#
-    param=
-    while test $n -ne 0; do
-      eval param=\$$n
-      test "$param" = "-" && break
-      sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
-      eval SBS_VALID_$sbs_param=1
-      n=`expr $n - 1`
-    done
-
-    if test "$param" != "-"; then 
-      echo "invalid parameter: $param" >&2
-      exit 1
-    fi
-
-    n=1
-    sbs_param=
-    while test $n -le $#; do
-      eval param=\$$n
-      case "$param" in
-        -)
-          break
-          ;;
-        -*|*=*)
-          sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
-          eval is_valid=\$SBS_VALID_$sbs_param
-          if test x$is_valid != x1; then
-            echo "invalid parameter: $param" >&2
-            exit 1
-          fi
-          ;;
-        *)
-          if test -z "$sbs_param"; then
-            echo "invalid parameter: $param" >&2
-            exit 1
-          fi
-          ;;
-      esac
-      n=`expr $n + 1`
+    op_delim=
+    while test $# -gt 0; do
+      if test -z "$op_delim"; then
+        case "$1" in
+          -)
+            op_delim=1
+            ;;
+          *)
+            sbs_param=`echo -n "$1" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
+            eval SBS_VALID_$sbs_param=1
+            ;;
+        esac
+      else
+        case "$1" in
+          -*|*=*)
+            sbs_param=`echo -n "$1" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
+            eval is_valid=\$SBS_VALID_$sbs_param
+            if test x$is_valid != x1; then
+              echo "invalid parameter: $1" >&2
+              exit 1
+            fi
+            ;;
+          *)
+            if test -z "$sbs_param"; then
+              echo "invalid parameter: $1" >&2
+              exit 1
+            fi
+            ;;
+        esac
+      fi
+      shift
     done
     exit 0
     ;;
-  xif|xifor)
-    mode=$1
+  xtest)
     shift
-    test $# -ne 0 || exit 0
-    n=1
-    param=
-    while test $n -le $#; do
-      eval param=\$$n
-      case "$param" in
-        -)
-          break
-          ;;
-        -*|*=*)
-          sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
-          eval SBS_SET_$sbs_param=1
-          ;;
-      esac
-      n=`expr $n + 1`
-    done
-
-    test "$param" = "-" || exit 0
-
-    n=`expr $n + 1`
-    sbs_param=
-    while test $n -le $#; do
-      eval param=\$$n
-      sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
-      eval is_set=\$SBS_SET_$sbs_param
-      if test $mode = if; then
-        test x$is_set = x1 || exit 1
-      else
-        test x$is_set = x1 && exit 0
-      fi
-      n=`expr $n + 1`
-    done
-    if test $mode = if; then
-      exit 0
+    if test x"$1" = "x!"; then
+      ret_false=0
+      ret_true=1
+      shift
     else
-      exit 1
+      ret_false=1
+      ret_true=0
     fi
-    ;;
-  xifhelp)
-    shift
-    test $# -ne 0 || exit 1
-    SBS_SET__H=1
-    SBS_SET__HELP=1
-    SBS_SET___HELP=1
-
-    n=1
-    sbs_param=
-    while test $n -le $#; do
-      eval param=\$$n
-      sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
-      eval is_set=\$SBS_SET_$sbs_param
-      test x$is_set = x1 && exit 0
-      n=`expr $n + 1`
+    if test x"$1" = xany; then
+      mode=any
+      shift
+    else
+      mode=all
+    fi
+    op_delim=
+    if_ops=
+    while test $# -gt 0; do
+      if test -z "$op_delim"; then
+        case "$1" in
+          -)
+            op_delim=1
+            ;;
+          *)
+            if_ops="$if_ops $1"
+            ;;
+        esac
+      else
+        sbs_param=`echo -n "$1" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
+        eval SBS_SET_$sbs_param=1
+      fi
+      shift
     done
-    exit 1
+
+    test -z "$if_ops" && exit 0
+
+    for ifop in $if_ops; do
+      sbs_param=`echo -n "$ifop" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
+      eval is_set=\$SBS_SET_$sbs_param
+      if test $mode = all; then
+        test x$is_set = x1 || exit $ret_false
+      else
+        test x$is_set = x1 && exit $ret_true
+      fi
+    done
+
+    if test $mode = all; then
+      exit $ret_ture
+    else
+      exit $ret_false
+    fi
     ;;
   xsource)
     shift
     tmp_file=/tmp/op_source$$.sh
-    cat <<EOF >$tmp_file
-#!/bin/sh
-rm -f $tmp_file
-EOF
+    echo "#!/bin/sh" >$tmp_file
     $0 dump "$@" >>$tmp_file
+    echo "rm -f $tmp_file" >>$tmp_file
     echo -n "$tmp_file"
     ;;
   x)
diff --git a/src/mkrule/mkrule b/src/mkrule/mkrule
--- a/src/mkrule/mkrule
+++ b/src/mkrule/mkrule
@@ -39,9 +39,7 @@ if test -n "$MKRULE" && test -z "$MKRULE_REDIRECT"; then
     exit $ret
   fi
 fi
-test -z "$CONFIG_TAR"      || TAR=$CONFIG_TAR
 test -n "$TAR"             || TAR=tar
-test -z "$CONFIG_INSTALL"  || INSTALL=$CONFIG_INSTALL
 test -n "$INSTALL"         || INSTALL=install
 
 test -n "$PREFIX"      || PREFIX=/usr/local
@@ -80,7 +78,7 @@ $script_name -v
   dist        generate rule that creates distribution tarball
   -v          print version
 
-First parameter specifies the mode. To get help on each mode run '$script_name MODE -help'
+First parameter specifies a mode. To get help on each mode run '$script_name MODE -help'
 EOF
 }
 
@@ -284,16 +282,16 @@ rel_path() {
   rel_path_ret=`echo -n "$dir_up/$dir_down" | sed 's:^/*$:.:' | sed 's:^/*::' | sed 's:/*$::'`
 }
 
-get_pofig() {
-  pofig -h >/dev/null 2>&1
+get_syscap() {
+  syscap -h >/dev/null 2>&1
   if test $? -ne 127; then
-    POFIG=pofig
+    SYSCAP=syscap
   else
-    $script_dir/pofig -h >/dev/null 2>&1
+    $script_dir/syscap -h >/dev/null 2>&1
     if test $? -ne 127; then
-      POFIG=$script_dir/pofig
+      SYSCAP=$script_dir/syscap
     else
-      echo "$script_name: error: pofig not found" >&2
+      echo "$script_name: error: syscap not found" >&2
       exit 1
     fi
   fi
@@ -384,7 +382,7 @@ mkobj() {
     exit 1
   fi
 
-  get_pofig
+  get_syscap
   get_cstem
   if test x$op_disable_mkdep = x; then
     get_mkdep
@@ -423,7 +421,7 @@ mkobj() {
     cc_cmd="$cc_cmd $op_cflags"
   fi
   
-  os_type=`$POFIG -os`
+  os_type=`$SYSCAP -os`
   case "$os_type" in
     gnulinux|*)
       obj_ext="o"
@@ -581,7 +579,7 @@ mkprog() {
     exit 1
   fi
 
-  get_pofig
+  get_syscap
   get_cstem
   
   cc_cmd=`$CSTEM -cmd`
@@ -590,7 +588,7 @@ mkprog() {
     exit 1
   fi
 
-  os_type=`$POFIG -os`
+  os_type=`$SYSCAP -os`
   case "$os_type" in
     gnulinux|*)
       exe_ext=
@@ -681,8 +679,8 @@ mklib() {
     exit 1
   fi
 
-  get_pofig
-  os_type=`$POFIG -os`
+  get_syscap
+  os_type=`$SYSCAP -os`
   case "$os_type" in
     gnulinux)
       cp_no_deref="--no-dereference"
@@ -1187,7 +1185,7 @@ EOF
 }
 
 if test $# -eq 0; then
-  echo "$script_name: error: no parameters passed" >&2
+  echo "$script_name: error: no parameters specified" >&2
   exit 1
 fi
 
