renamed fmkconfigure -> fmconfigure, fmkinstall -> fminstall, fmkpackage -> fmpackage

diff --git a/src/fmconfigure/fmconfigure b/src/fmconfigure/fmconfigure
--- a/src/fmconfigure/fmconfigure
+++ b/src/fmconfigure/fmconfigure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Formake fmkconfigure
+# Formake fmconfigure
 #
 # Copyright (c) 2015-2017, Oleksiy Chernyavskyy
 # All rights reserved.
@@ -25,7 +25,7 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-version_string="fmkconfigure 1.0"
+version_string="fmconfigure 1.0"
 
 script_name=`basename "$0"`
 script_options="$@"
@@ -52,7 +52,7 @@ $script_name OPTIONS
   -syscap ".."       probe a system with syscap test tool
   -sh CODE           insert shell string
   -build-h           generate BUILDROOT/build.h config header
-  -fmkinstall        install Formake scripts into package formake directory
+  -fminstall        install Formake scripts into package formake directory
   -f                 force to overwrite existing configure script if found
   -o FILE            output script file [$out_file]
   -v                 print version
@@ -123,8 +123,8 @@ while test $# -gt 0; do
     -o)
       current_opt=o
       ;;
-    -fmkinstall)
-      op_fmkinstall=1
+    -fminstall)
+      op_fminstall=1
       current_opt=
       ;;
     -f)
@@ -195,11 +195,11 @@ if test -n "$op_cc$op_cxx"; then
 fi
 formake_scripts=`echo -n "$formake_scripts" | sed 's/^ *//'`
 
-if test x$op_fmkinstall = x1; then
-  if fmkinstall -h >/dev/null; then
+if test x$op_fminstall = x1; then
+  if fminstall -h >/dev/null; then
     :
   else
-    echo "$script_name: fmkinstall script not found" >&2
+    echo "$script_name: fminstall script not found" >&2
     clean_exit 1
   fi
   test -d $out_file_dir/formake || mkdir -p $out_file_dir/formake
@@ -207,14 +207,14 @@ if test x$op_fmkinstall = x1; then
     echo "$script_name: could not create Formake directory $out_file_dir/formake" >&2
     clean_exit 1
   fi
-  fmkinstall -d $out_file_dir/formake -std $formake_scripts || clean_exit 1
+  fminstall -d $out_file_dir/formake -std $formake_scripts || clean_exit 1
 fi
 
 rm_out_file=1
 cat <<TOP_EOF >$out_file
 #!/bin/sh
 ################################################################################
-# Generated by Formake fmkconfigure
+# Generated by Formake fmconfigure
 TOP_EOF
 date >/dev/null 2>&1
 if test $? -eq 0; then
