added 'dist' mode in mkrule, many changes and fixes

diff --git a/src/cstem/cstem b/src/cstem/cstem
--- a/src/cstem/cstem
+++ b/src/cstem/cstem
@@ -88,8 +88,8 @@ cat <<EOF
 Configure and probe C compiler
 
 $script_name [options]
-$script_name config [-cc=CMD] [-cflags=FLAGS]
-$script_name probe [-cc=CMD] [-cflags=FLAGS] [-f1|-f2|-f3]
+$script_name config [-cc CMD] [-cflags=FLAGS]
+$script_name probe [-cc CMD] [-cflags=FLAGS] [-f1|-f2|-f3]
 
 By default $script_name prints information about configured compiler
  -id            get compiler id
@@ -107,11 +107,11 @@ By default $script_name prints information about configured compiler
 
 
 Config mode. Probe compiler and generate config file
- -cc=CMD        specify compiler command with optional flags
+ -cc CMD        specify compiler command with optional flags
  -cflags=FLAGS  specify compiler flags
 
 Probe mode. Probe compiler and print information to a standard output
- -cc=CMD        specify compiler command with optional flags
+ -cc CMD        specify compiler command with optional flags
  -cflags=FLAGS  specify compiler flags
  -f1            print in format 1> VAR="VALUE"
  -f2            print in format 2> FIELD: VALUE
@@ -1016,13 +1016,15 @@ case x"$1" in
 esac
 
 if test x$mode_config$mode_probe = x1; then
+  current_opt=
   while test $# -gt 0; do
     case "$1" in
-      -cc=*)
-        probe_cc_cmd=`echo -n "$1" | sed 's/^[^=]*=//'`
+      -cc)
+        current_opt=cc
         ;;
       -cflags=*)
         probe_cc_flags=`echo -n "$1" | sed 's/^[^=]*=//'`
+        current_opt=
         ;;
       -f1|-f2|-f3)
         if test x$mode_probe = x; then
@@ -1030,10 +1032,19 @@ if test x$mode_config$mode_probe = x1; then
           exit 1
         fi
         out_format=`echo -n "$1" | sed 's/^-f//'`
+        current_opt=
         ;;
       *)
-        printf "%s\n" "$script_name: invalid parameter $1" >&2
-        exit 1
+        case "$current_opt" in
+          cc)
+            probe_cc_cmd=$1
+            current_opt=
+            ;;
+          *)
+            printf "%s\n" "$script_name: invalid parameter $1" >&2
+            exit 1
+            ;;
+        esac
         ;;
     esac
     shift
diff --git a/src/mkconfigure/mkconfigure b/src/mkconfigure/mkconfigure
--- a/src/mkconfigure/mkconfigure
+++ b/src/mkconfigure/mkconfigure
@@ -63,22 +63,10 @@ while test $# -gt 0; do
       clean_exit 0
       ;;
     -name)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -name requires argument" >&2
-        clean_exit 1
-      fi
-      op_pkgname=$1
-      current_opt=
+      current_opt=name
       ;;
     -ver)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -ver requires argument" >&2
-        clean_exit 1
-      fi
-      op_pkgver=$1
-      current_opt=
+      current_opt=ver
       ;;
     -params=*)
       op_params=`echo -n "$1" | sed 's/^[^=]*=//'`
@@ -101,37 +89,13 @@ while test $# -gt 0; do
       current_opt=
       ;;
     -iflib)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -iflib requires argument" >&2
-        clean_exit 1
-      fi
-      op_iflib=1
-      params=$1
-      eval iflib${iflib_index}_params=\$params
-      iflib_index=`expr $iflib_index + 1`
-      current_opt=
+      current_opt=iflib
       ;;
     -iftool)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -iftool requires argument" >&2
-        clean_exit 1
-      fi
-      op_iftool=1
-      params=$1
-      eval iftool${iftool_index}_params=\$params
-      iftool_index=`expr $iftool_index + 1`
-      current_opt=
+      current_opt=iftool
       ;;
     -sh)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -sh requires argument" >&2
-        clean_exit 1
-      fi
-      op_sh=$1
-      current_opt=
+      current_opt=sh
       ;;
     -build-h)
       op_build_h=1
@@ -146,29 +110,57 @@ while test $# -gt 0; do
       current_opt=
       ;;
     -o)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -o requires argument" >&2
-        clean_exit 1
-      fi
-      out_file=$1
-      if test -d "$out_file"; then
-        out_file="$out_file/configure"
-      fi
-      out_file_dir=`dirname "$out_file"`
-      if test ! -d "$out_file_dir"; then
-        echo "$script_name: error. Directory not found: $out_file_dir" >&2
-        clean_exit 1
-      fi
-      current_opt=
+      current_opt=o
       ;;
     -mkpackage)
       op_mkpackage=1
       current_opt=
       ;;
     *)
-      echo "$script_name: error. Invalid parameter: $1" >&2
-      clean_exit 1
+      case "$current_opt" in
+        name)
+          op_pkgname=$1
+          current_opt=
+          ;;
+        ver)
+          op_pkgver=$1
+          current_opt=
+          ;;
+        iflib)
+          op_iflib=1
+          params=$1
+          eval iflib${iflib_index}_params=\$params
+          iflib_index=`expr $iflib_index + 1`
+          current_opt=
+          ;;
+        iftool)
+          op_iftool=1
+          params=$1
+          eval iftool${iftool_index}_params=\$params
+          iftool_index=`expr $iftool_index + 1`
+          current_opt=
+          ;;
+        sh)
+          op_sh=$1
+          current_opt=
+          ;;
+        o)
+          out_file=$1
+          if test -d "$out_file"; then
+            out_file="$out_file/configure"
+          fi
+          out_file_dir=`dirname "$out_file"`
+          if test ! -d "$out_file_dir"; then
+            echo "$script_name: error. Directory not found: $out_file_dir" >&2
+            clean_exit 1
+          fi
+          current_opt=
+          ;;
+        *)
+          echo "$script_name: error. Invalid parameter: $1" >&2
+          clean_exit 1
+          ;;
+      esac
       ;;
   esac
   shift
@@ -354,10 +346,10 @@ if test -n "$op_cstem$op_cstemx"; then
 # PROBE AND CONFIGURE COMPILERS
 TOP_EOF
   if test x$op_cstem = x1; then
-    echo "cstem config -cc=\$CC -cflags=\"\$CFLAGS\"" >>$out_file
+    echo "cstem config -cc \$CC -cflags=\"\$CFLAGS\"" >>$out_file
   fi
   if test x$op_cstemx = x1; then
-    echo "cstem+ config -cc=\$CXX -cflags=\"\$CXXFLAGS\"" >>$out_file
+    echo "cstem+ config -cc \$CXX -cflags=\"\$CXXFLAGS\"" >>$out_file
   fi
   echo "" >>$out_file
 fi
@@ -371,11 +363,11 @@ TOP_EOF
   while test $idx -lt $iflib_index; do
     eval iflib_params=\$iflib${idx}_params
     if test x$op_cstem$op_cstemx = x11; then
-      echo "iflib -cc $iflib_params -log=\"configure.log\" || exit 1" >>$out_file
+      echo "iflib -cc $iflib_params -log configure.log || exit 1" >>$out_file
     elif test x$op_cstemx = x1; then
-      echo "iflib -cxx $iflib_params -log=\"configure.log\" || exit 1" >>$out_file
+      echo "iflib -cxx $iflib_params -log configure.log || exit 1" >>$out_file
     else
-      echo "iflib -cc $iflib_params -log=\"configure.log\" || exit 1" >>$out_file
+      echo "iflib -cc $iflib_params -log configure.log || exit 1" >>$out_file
     fi
     idx=`expr $idx + 1`
   done
@@ -410,9 +402,9 @@ if test x$op_no_install = x; then
 
 ################################################################################
 # MKRULE
-mkrule config -prefix=$PREFIX -exec-prefix=$EXEC_PREFIX -bindir=$BINDIR -sbindir=$SBINDIR \
-          -libexecdir=$LIBEXECDIR -libdir=$LIBDIR -incdir=$INCDIR -etcdir=$ETCDIR \
-          -sharedir=$PACKAGE_SHAREDIR -mandir=$MANDIR -docdir=$PACKAGE_DOCDIR
+mkrule config -prefix $PREFIX -exec-prefix $EXEC_PREFIX -bindir $BINDIR -sbindir $SBINDIR \
+          -libexecdir $LIBEXECDIR -libdir $LIBDIR -incdir $INCDIR -etcdir $ETCDIR \
+          -sharedir $PACKAGE_SHAREDIR -mandir $MANDIR -docdir $PACKAGE_DOCDIR
 TOP_EOF
 fi
 
diff --git a/src/mkdep/mkdep b/src/mkdep/mkdep
--- a/src/mkdep/mkdep
+++ b/src/mkdep/mkdep
@@ -14,23 +14,24 @@ print_help() {
 cat <<EOF
 Generate dependencies of C/C++ source files for Makefile
 
-${script_name} [-c++] [-cc=cmd] [-o object] [-cflags=flags] [-I<path>] [-D<define>[=value]] [-stdout|-d file] src..
+${script_name} [-c++] [-cc CMD] [-o OBJECT] [-cflags=FLAGS] [-I<PATH>] [-D<NAME>[=VALUE]] [-stdout|-d FILE] SRC..
 
 Options:
   -c++              force using C++ compiler [autodetect]
-  -cc=cmd           compiler command
-  -o object         output object file
-  -cflags=flags     compiler flags
-  -I<path>          headers path
-  -D<name>[=value]  define a CPP macro
+  -cc CMD           compiler command
+  -o OBJECT         output object file
+  -cflags=FLAGS     compiler flags
+  -I<PATH>          headers path
+  -D<NAME>[=VALUE]  define a CPP macro
   -stdout           print dependency information to a standard output
-  -d file           specify output dependency file
-  src..             source files
+  -d FILE           specify output dependency file
+  SRC..             source files
 EOF
 }
 
 source_num=0
 op_sources=
+current_opt=
 while test $# -gt 0; do
   case $1 in
     -h|-help|--help)
@@ -39,58 +40,66 @@ while test $# -gt 0; do
       ;;
     -c++)
       op_cxx=1
+      current_opt=
       ;;
     -cc)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -cc requires argument" >&2
-        exit 1
-      fi
-      op_cc=$1
+      current_opt=cc
       ;;
     -o)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -o requires argument" >&2
-        exit 1
-      fi
-      op_object=$1
+      current_opt=o
       ;;
     -cflags=*)
       op_cflags=`echo -n "$1" | sed 's/^-cflags=//'`
+      current_opt=
       ;;
     -I*)
       op_cflags2="$op_cflags2 $1"
+      current_opt=
       ;;
     -D*)
       op_cflags2="$op_cflags2 $1"
+      current_opt=
       ;;
     -stdout)
       op_stdout=1
       op_out_file=
+      current_opt=
       ;;
     -d)
-      shift
-      if test -z "$1"; then
-        echo "$script_name: error. Parameter -d requires argument" >&2
-        exit 1
-      fi
-      op_out_file=$1
       op_stdout=
+      current_opt=d
       ;;
     *.c)
       op_sources="$op_sources $1"
       source_num=`expr $source_num + 1`
       have_c=1
+      current_opt=
       ;;
     *.C|*.[Cc][Cc]|*.[Cc][Pp][Pp]|*.[Cc][Xx][Xx])
       op_sources="$op_sources $1"
       source_num=`expr $source_num + 1`
       have_cxx=1
+      current_opt=
       ;;
     *)
-      echo "$script_name: error. Invalid parameter: $1" >&2
-      exit 1
+      case "$current_opt" in
+        cc)
+          op_cc=$1
+          current_opt=
+          ;;
+        o)
+          op_object=$1
+          current_opt=
+          ;;
+        d)
+          op_out_file=$1
+          current_opt=
+          ;;
+        *)
+          echo "$script_name: error. Invalid parameter: $1" >&2
+          exit 1
+          ;;
+      esac
       ;;
   esac
   shift
diff --git a/src/mkmkmf/test/formake/cstem b/src/mkmkmf/test/formake/cstem
--- a/src/mkmkmf/test/formake/cstem
+++ b/src/mkmkmf/test/formake/cstem
@@ -4,31 +4,55 @@
 #
 
 abs_path() {
-  arg=$1
-  if test -e "$arg"; then
-    if test -d $arg; then
-      file=
+  _sub_orig_dir=`pwd`
+  if test $# = 0; then
+    abs_path_ret=
+    return
+  fi
+  if test $# = 2; then
+    _arg_orig_dir=$1
+    _arg=$2
+    if echo -n "$_arg" | grep "^/" > /dev/null; then
+      :
     else
-      file=`basename -- $arg`
-      arg=`dirname -- $arg`
+      _arg=`echo -n "$_arg_orig_dir/$_arg" | sed 's!//*!/!g'`
     fi
-
-    cd $arg
-    abs_path_ret=`pwd`
-    if test x"$file" != "x"; then
-      abs_path_ret="$abs_path_ret/$file"
-    fi
-
-    cd $orig_dir
   else
-    if echo -n "$arg" | grep "^/" > /dev/null; then
-      abs_path_ret="$arg"
+    _arg=$1
+  fi
+  if test -e "$_arg"; then
+    if test -d $_arg; then
+      _file=
     else
-      abs_path_ret="$orig_dir/$arg"
+      _file=`basename -- $_arg`
+      _arg=`dirname -- $_arg`
     fi
+
+    cd $_cd_param $_arg
+    abs_path_ret=`pwd`
+    if test x"$_file" != "x"; then
+      abs_path_ret="$abs_path_ret/$_file"
+    fi
+
+    cd $_cd_param $_sub_orig_dir
+  else
+    if echo -n "$_arg" | grep "^/" > /dev/null; then
+      abs_path_ret="$_arg"
+    else
+      abs_path_ret="$_sub_orig_dir/$_arg"
+    fi
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#//*#/#g'`
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/*$#/#'`
+    string_prev=
+    while test "x$abs_path_ret" != "x$string_prev" ; do
+      string_prev=$abs_path_ret
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/[^/][^/][^/][^/]*/\.\./#/#g' | sed 's#/[^/][^/.]/\.\./#/#g' | sed 's#/[^/.][^/]/\.\./#/#g' | sed 's#/[^/.]/\.\./#/#g'`
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#^/\.\./#/#' | sed 's#^/\.\.$#/#'`
+      abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/\./#/#g' | sed 's#/\.$#/#'`
+    done
+    abs_path_ret=`echo -n "$abs_path_ret" | sed 's#/$##' | sed 's#^$#/#'`
   fi
 }
-
 
 script_name=`basename $0`
 orig_dir=`pwd`
@@ -64,8 +88,8 @@ cat <<EOF
 Configure and probe C compiler
 
 $script_name [options]
-$script_name config [-cc=CMD] [-cflags=FLAGS]
-$script_name probe [-cc=CMD] [-cflags=FLAGS] [-f1|-f2|-f3]
+$script_name config [-cc CMD] [-cflags=FLAGS]
+$script_name probe [-cc CMD] [-cflags=FLAGS] [-f1|-f2|-f3]
 
 By default $script_name prints information about configured compiler
  -id            get compiler id
@@ -83,11 +107,11 @@ By default $script_name prints information about configured compiler
 
 
 Config mode. Probe compiler and generate config file
- -cc=CMD        specify compiler command with optional flags
+ -cc CMD        specify compiler command with optional flags
  -cflags=FLAGS  specify compiler flags
 
 Probe mode. Probe compiler and print information to a standard output
- -cc=CMD        specify compiler command with optional flags
+ -cc CMD        specify compiler command with optional flags
  -cflags=FLAGS  specify compiler flags
  -f1            print in format 1> VAR="VALUE"
  -f2            print in format 2> FIELD: VALUE
@@ -911,20 +935,20 @@ perform_probe() {
     if test x$have_pofig = x1; then
       case `pofig -os` in
         aix)
-          cc_list="cc xlc gcc"
+          cc_list="cc xlc gcc c99"
           ;;
-        sunos)
-          cc_list="cc gcc"
+        solaris)
+          cc_list="cc gcc c99"
           ;;
         irix)
           cc_list="cc c99 gcc c89"
           ;;
         gnulinux)
-          cc_list="gcc cc"
+          cc_list="gcc cc c99"
           ;;
       esac
     else
-      cc_list="gcc cc"
+      cc_list="gcc cc c99"
     fi
 
     for cc_cmd in $cc_list; do
@@ -992,13 +1016,15 @@ case x"$1" in
 esac
 
 if test x$mode_config$mode_probe = x1; then
+  current_opt=
   while test $# -gt 0; do
     case "$1" in
-      -cc=*)
-        probe_cc_cmd=`echo -n "$1" | sed 's/^[^=]*=//'`
+      -cc)
+        current_opt=cc
         ;;
       -cflags=*)
         probe_cc_flags=`echo -n "$1" | sed 's/^[^=]*=//'`
+        current_opt=
         ;;
       -f1|-f2|-f3)
         if test x$mode_probe = x; then
@@ -1006,10 +1032,19 @@ if test x$mode_config$mode_probe = x1; then
           exit 1
         fi
         out_format=`echo -n "$1" | sed 's/^-f//'`
+        current_opt=
         ;;
       *)
-        printf "%s\n" "$script_name: invalid parameter $1" >&2
-        exit 1
+        case "$current_opt" in
+          cc)
+            probe_cc_cmd=$1
+            current_opt=
+            ;;
+          *)
+            printf "%s\n" "$script_name: invalid parameter $1" >&2
+            exit 1
+            ;;
+        esac
         ;;
     esac
     shift
diff --git a/src/mkmkmf/test/formake/iflib b/src/mkmkmf/test/formake/iflib
--- a/src/mkmkmf/test/formake/iflib
+++ b/src/mkmkmf/test/formake/iflib
@@ -88,12 +88,12 @@ $script_name options
  -cstr TEXT      one line source string
  -cflags=FLAGS   compiler flags
  -ldflags=FLAGS  linker flags
- -cc[=cmd]       use C compiler. Optional compiler command can be passed
- -cxx[=cmd]      use C++ compiler. Optional compiler command can be passed
+ -cc [CMD]       use C compiler. Optional compiler command can be passed
+ -cxx [CMD]      use C++ compiler. Optional compiler command can be passed
  "#if* ..."      test preprocessor condition directives
  *.h|*.hh        lib include headers. Different file extensions are recognized
  *.c|*.cc        test source files. Different file extensions are recognized
- -log[=FILE]     print log to stdout or specified file
+ -log [FILE]     print log to stdout or specified file
  -short          run short test - do not check compiler, linker, cflags,
                  ldflags, includes and libraries
  -no-ld          disable any ld tests
@@ -163,9 +163,7 @@ while test $# -gt 0; do
       current_opt=rval
       ;;
     -cstr)
-      shift
-      op_cstr=$1
-      current_opt=
+      current_opt=cstr
       ;;
     -cflags=*)
       arg=`echo -n "$param" | sed 's/^[^=]*=//'`
@@ -179,32 +177,18 @@ while test $# -gt 0; do
       ;;
     -cc)
       cc_type=cc
-      current_opt=
-      ;;
-    -cc=*)
-      cc_type=cc
-      arg=`echo -n "$param" | sed 's/^[^=]*=//'`
-      op_cmd=$arg
-      current_opt=
+      current_opt=cc
       ;;
     -cxx)
       cc_type=cxx
-      current_opt=
-      ;;
-    -cxx=*)
-      cc_type=cxx
-      arg=`echo -n "$param" | sed 's/^[^=]*=//'`
-      op_cmd=$arg
-      current_opt=
+      current_opt=cxx
       ;;
     -log)
       op_echo_log=1
       current_opt=
       ;;
-    -log=*)
-      arg=`echo -n "$param" | sed 's/^[^=]*=//'`
-      op_log_file=$arg
-      current_opt=
+    -log)
+      current_opt=log
       ;;
     -[ID]*)
       op_cflags="$op_cflags $param"
@@ -260,7 +244,19 @@ while test $# -gt 0; do
         echo "$script_name: error: bad option $param" >&2
         exit 1
       fi
-      case $current_opt in
+      case "$current_opt" in
+        cstr)
+          op_cstr=$1
+          current_opt=
+          ;;
+        cc|cxx)
+          op_cmd=$param
+          current_opt=
+          ;;
+        log)
+          op_log_file=$param
+          current_opt=
+          ;;
         inc)
           op_inc="$op_inc $param"
           ;;
@@ -600,7 +596,7 @@ EOF
       def_name=`echo -n "$def_string" | sed 's/[^a-zA-Z0-9_].*//'`
       inv_chars=`echo -n "$def_name" | sed 's/[_a-zA-Z0-9]//g'`
       if test -n "$inv_chars" || echo -n "$def_name" | grep "^[0-9]" > /dev/null; then
-        echo "$script_name: error invalid macro $def_name"
+        echo "$script_name: error invalid macro $def_name" >&2
         exit 1
       fi
       rpart=`echo -n "$def_string" | sed 's/[a-zA-Z0-9_]*//'`
@@ -622,7 +618,7 @@ EOF
             opstr="=="
             ;;
           *)
-            echo "$script_name: error invalid argument $def_string"
+            echo "$script_name: error invalid argument $def_string" >&2
             exit 1
             ;;
         esac
@@ -818,19 +814,21 @@ fi
 # CHECKING SOURCE FILES
 if test -n "$op_src"; then
   for src in $op_src; do
-    if echo -n "$src" | grep "^/" > /dev/null; then : ; else
-      src="$orig_dir/$src"
+    if echo -n "$src" | grep "^/" > /dev/null; then 
+      src_full=$src
+    else
+      src_full="$orig_dir/$src"
     fi
 
     echo_status "%s" "checking source file $src ... "
 
-    if test ! -f $src; then
+    if test ! -f $src_full; then
       echo_status "%s\n" "Failed"
       echo_status "%s\n" "  file $src not found"
       script_exit 1
     fi
-    cp $src .
-    src_base=`basename $src`
+    cp $src_full .
+    src_base=`basename $src_full`
 
     echo "\$ $CC_CMD -c -o test.o $src_base" >> iflib.log
     $CC_CMD -c -o test.o $src_base >> iflib.log 2>&1
diff --git a/src/mkmkmf/test/formake/mkbuildroot b/src/mkmkmf/test/formake/mkbuildroot
--- a/src/mkmkmf/test/formake/mkbuildroot
+++ b/src/mkmkmf/test/formake/mkbuildroot
@@ -27,7 +27,7 @@ case x$1 in
 esac
 
 if test $# -ne 2; then
-  echo "$script_name: error: invalid number of parameters"
+  echo "$script_name: error: invalid number of parameters" >&2
   exit 1
 fi
 
@@ -35,7 +35,7 @@ srcroot=$1
 buildroot=$2
 
 if test ! -d $srcroot; then
-  echo "$script_name: error: invalid source root path"
+  echo "$script_name: error: invalid source root path" >&2
   exit 1
 fi
 
@@ -44,7 +44,7 @@ if test ! -d $buildroot; then
 fi
 
 if test ! -d $buildroot; then
-  echo "$script_name: error: could not create build root dir"
+  echo "$script_name: error: could not create build root dir" >&2
   exit 1
 fi
 
diff --git a/src/mkmkmf/test/formake/optool b/src/mkmkmf/test/formake/optool
--- a/src/mkmkmf/test/formake/optool
+++ b/src/mkmkmf/test/formake/optool
@@ -28,7 +28,7 @@ EOF
     shift
     while test $# -gt 0; do
       case "$1" in
-        -*)
+        -*|*=*)
           if test -n "$sbs_param"; then
             test -n "$sbs_param_val$sbs_param_set" || sbs_param_val=1
             if test $mode = rc; then
@@ -48,6 +48,10 @@ EOF
                   exit 1
                 fi
                 op_prefix=`echo -n "$1" | sed 's/[^a-zA-Z0-9_]//g'`
+                if test -z "$op_prefix"; then 
+                  echo "$script_name: error: invalid prefix '$1'" >&2
+                  exit 1
+                fi
                 param_skip=1
                 ;;
               -nc)
@@ -61,7 +65,7 @@ EOF
               -)
                 disable_special=1
                 ;;
-              -*)
+              *)
                 sbs_param=`echo -n "$1" | sed "s/^-*//" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g'`
                 sbs_param="$op_prefix$sbs_param"
                 if test -z $no_case_change; then
@@ -70,7 +74,7 @@ EOF
                 sbs_param_val=
                 sbs_param_set=
                 case "$1" in
-                  -*=*)
+                  *=*)
                     sbs_param_val=`echo -n "$1" | sed 's/^[^=]*=//'`
                     sbs_param_set=1
                     ;;
@@ -80,7 +84,7 @@ EOF
           fi
           ;;
         *)
-          if test -z "$sbs_param"; then
+          if test -z "$sbs_param" || test x$sbs_param_set = x1; then
             echo "invalid parameter: $1" >&2
             exit 1
           fi
@@ -129,7 +133,7 @@ EOF
         -)
           break
           ;;
-        -*)
+        -*|*=*)
           sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
           eval is_valid=\$SBS_VALID_$sbs_param
           if test x$is_valid != x1; then
@@ -160,7 +164,7 @@ EOF
         -)
           break
           ;;
-        -*)
+        -*|*=*)
           sbs_param=`echo -n "$param" | sed 's/=.*//' | tr '-' '_' | sed 's/[^a-zA-Z0-9_]//g' | tr '[a-z]' '[A-Z]'`
           eval SBS_SET_$sbs_param=1
           ;;
diff --git a/src/optool/optool b/src/optool/optool
--- a/src/optool/optool
+++ b/src/optool/optool
@@ -48,6 +48,10 @@ EOF
                   exit 1
                 fi
                 op_prefix=`echo -n "$1" | sed 's/[^a-zA-Z0-9_]//g'`
+                if test -z "$op_prefix"; then 
+                  echo "$script_name: error: invalid prefix '$1'" >&2
+                  exit 1
+                fi
                 param_skip=1
                 ;;
               -nc)
